package com.survey.panelsns.model.entity;

import java.util.Date;

public class Ques {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ques.id
     *
     * @mbggenerated Sun Jul 29 21:04:38 CST 2012
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ques.ques_naire_id
     *
     * @mbggenerated Sun Jul 29 21:04:38 CST 2012
     */
    private Long quesNaireId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ques.type
     *
     * @mbggenerated Sun Jul 29 21:04:38 CST 2012
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ques.serial_no
     *
     * @mbggenerated Sun Jul 29 21:04:38 CST 2012
     */
    private Integer serialNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ques.busi_no
     *
     * @mbggenerated Sun Jul 29 21:04:38 CST 2012
     */
    private String busiNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ques.title
     *
     * @mbggenerated Sun Jul 29 21:04:38 CST 2012
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ques.content
     *
     * @mbggenerated Sun Jul 29 21:04:38 CST 2012
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ques.descript
     *
     * @mbggenerated Sun Jul 29 21:04:38 CST 2012
     */
    private String descript;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ques.must_answer
     *
     * @mbggenerated Sun Jul 29 21:04:38 CST 2012
     */
    private Integer mustAnswer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ques.create_date
     *
     * @mbggenerated Sun Jul 29 21:04:38 CST 2012
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ques.update_date
     *
     * @mbggenerated Sun Jul 29 21:04:38 CST 2012
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ques.version
     *
     * @mbggenerated Sun Jul 29 21:04:38 CST 2012
     */
    private Integer version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ques.remark
     *
     * @mbggenerated Sun Jul 29 21:04:38 CST 2012
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ques.id
     *
     * @return the value of ques.id
     *
     * @mbggenerated Sun Jul 29 21:04:38 CST 2012
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ques.id
     *
     * @param id the value for ques.id
     *
     * @mbggenerated Sun Jul 29 21:04:38 CST 2012
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ques.ques_naire_id
     *
     * @return the value of ques.ques_naire_id
     *
     * @mbggenerated Sun Jul 29 21:04:38 CST 2012
     */
    public Long getQuesNaireId() {
        return quesNaireId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ques.ques_naire_id
     *
     * @param quesNaireId the value for ques.ques_naire_id
     *
     * @mbggenerated Sun Jul 29 21:04:38 CST 2012
     */
    public void setQuesNaireId(Long quesNaireId) {
        this.quesNaireId = quesNaireId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ques.type
     *
     * @return the value of ques.type
     *
     * @mbggenerated Sun Jul 29 21:04:38 CST 2012
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ques.type
     *
     * @param type the value for ques.type
     *
     * @mbggenerated Sun Jul 29 21:04:38 CST 2012
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ques.serial_no
     *
     * @return the value of ques.serial_no
     *
     * @mbggenerated Sun Jul 29 21:04:38 CST 2012
     */
    public Integer getSerialNo() {
        return serialNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ques.serial_no
     *
     * @param serialNo the value for ques.serial_no
     *
     * @mbggenerated Sun Jul 29 21:04:38 CST 2012
     */
    public void setSerialNo(Integer serialNo) {
        this.serialNo = serialNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ques.busi_no
     *
     * @return the value of ques.busi_no
     *
     * @mbggenerated Sun Jul 29 21:04:38 CST 2012
     */
    public String getBusiNo() {
        return busiNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ques.busi_no
     *
     * @param busiNo the value for ques.busi_no
     *
     * @mbggenerated Sun Jul 29 21:04:38 CST 2012
     */
    public void setBusiNo(String busiNo) {
        this.busiNo = busiNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ques.title
     *
     * @return the value of ques.title
     *
     * @mbggenerated Sun Jul 29 21:04:38 CST 2012
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ques.title
     *
     * @param title the value for ques.title
     *
     * @mbggenerated Sun Jul 29 21:04:38 CST 2012
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ques.content
     *
     * @return the value of ques.content
     *
     * @mbggenerated Sun Jul 29 21:04:38 CST 2012
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ques.content
     *
     * @param content the value for ques.content
     *
     * @mbggenerated Sun Jul 29 21:04:38 CST 2012
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ques.descript
     *
     * @return the value of ques.descript
     *
     * @mbggenerated Sun Jul 29 21:04:38 CST 2012
     */
    public String getDescript() {
        return descript;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ques.descript
     *
     * @param descript the value for ques.descript
     *
     * @mbggenerated Sun Jul 29 21:04:38 CST 2012
     */
    public void setDescript(String descript) {
        this.descript = descript;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ques.must_answer
     *
     * @return the value of ques.must_answer
     *
     * @mbggenerated Sun Jul 29 21:04:38 CST 2012
     */
    public Integer getMustAnswer() {
        return mustAnswer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ques.must_answer
     *
     * @param mustAnswer the value for ques.must_answer
     *
     * @mbggenerated Sun Jul 29 21:04:38 CST 2012
     */
    public void setMustAnswer(Integer mustAnswer) {
        this.mustAnswer = mustAnswer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ques.create_date
     *
     * @return the value of ques.create_date
     *
     * @mbggenerated Sun Jul 29 21:04:38 CST 2012
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ques.create_date
     *
     * @param createDate the value for ques.create_date
     *
     * @mbggenerated Sun Jul 29 21:04:38 CST 2012
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ques.update_date
     *
     * @return the value of ques.update_date
     *
     * @mbggenerated Sun Jul 29 21:04:38 CST 2012
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ques.update_date
     *
     * @param updateDate the value for ques.update_date
     *
     * @mbggenerated Sun Jul 29 21:04:38 CST 2012
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ques.version
     *
     * @return the value of ques.version
     *
     * @mbggenerated Sun Jul 29 21:04:38 CST 2012
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ques.version
     *
     * @param version the value for ques.version
     *
     * @mbggenerated Sun Jul 29 21:04:38 CST 2012
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ques.remark
     *
     * @return the value of ques.remark
     *
     * @mbggenerated Sun Jul 29 21:04:38 CST 2012
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ques.remark
     *
     * @param remark the value for ques.remark
     *
     * @mbggenerated Sun Jul 29 21:04:38 CST 2012
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }
}