package com.survey.panelsns.model.entity;

public class Answer {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column answer.id
	 * @mbggenerated  Tue Sep 18 00:39:07 CST 2012
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column answer.answer_mess_id
	 * @mbggenerated  Tue Sep 18 00:39:07 CST 2012
	 */
	private Long answerMessId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column answer.user_id
	 * @mbggenerated  Tue Sep 18 00:39:07 CST 2012
	 */
	private Long userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column answer.naire_id
	 * @mbggenerated  Tue Sep 18 00:39:07 CST 2012
	 */
	private Long naireId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column answer.page_no
	 * @mbggenerated  Tue Sep 18 00:39:07 CST 2012
	 */
	private Integer pageNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column answer.ques_id
	 * @mbggenerated  Tue Sep 18 00:39:07 CST 2012
	 */
	private Long quesId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column answer.ques_no
	 * @mbggenerated  Tue Sep 18 00:39:07 CST 2012
	 */
	private Integer quesNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column answer.ques_opt_id
	 * @mbggenerated  Tue Sep 18 00:39:07 CST 2012
	 */
	private Long quesOptId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column answer.ques_opt_no
	 * @mbggenerated  Tue Sep 18 00:39:07 CST 2012
	 */
	private Integer quesOptNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column answer.answer_val
	 * @mbggenerated  Tue Sep 18 00:39:07 CST 2012
	 */
	private String answerVal;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column answer.remark
	 * @mbggenerated  Tue Sep 18 00:39:07 CST 2012
	 */
	private String remark;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column answer.id
	 * @return  the value of answer.id
	 * @mbggenerated  Tue Sep 18 00:39:07 CST 2012
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column answer.id
	 * @param id  the value for answer.id
	 * @mbggenerated  Tue Sep 18 00:39:07 CST 2012
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column answer.answer_mess_id
	 * @return  the value of answer.answer_mess_id
	 * @mbggenerated  Tue Sep 18 00:39:07 CST 2012
	 */
	public Long getAnswerMessId() {
		return answerMessId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column answer.answer_mess_id
	 * @param answerMessId  the value for answer.answer_mess_id
	 * @mbggenerated  Tue Sep 18 00:39:07 CST 2012
	 */
	public void setAnswerMessId(Long answerMessId) {
		this.answerMessId = answerMessId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column answer.user_id
	 * @return  the value of answer.user_id
	 * @mbggenerated  Tue Sep 18 00:39:07 CST 2012
	 */
	public Long getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column answer.user_id
	 * @param userId  the value for answer.user_id
	 * @mbggenerated  Tue Sep 18 00:39:07 CST 2012
	 */
	public void setUserId(Long userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column answer.naire_id
	 * @return  the value of answer.naire_id
	 * @mbggenerated  Tue Sep 18 00:39:07 CST 2012
	 */
	public Long getNaireId() {
		return naireId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column answer.naire_id
	 * @param naireId  the value for answer.naire_id
	 * @mbggenerated  Tue Sep 18 00:39:07 CST 2012
	 */
	public void setNaireId(Long naireId) {
		this.naireId = naireId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column answer.page_no
	 * @return  the value of answer.page_no
	 * @mbggenerated  Tue Sep 18 00:39:07 CST 2012
	 */
	public Integer getPageNo() {
		return pageNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column answer.page_no
	 * @param pageNo  the value for answer.page_no
	 * @mbggenerated  Tue Sep 18 00:39:07 CST 2012
	 */
	public void setPageNo(Integer pageNo) {
		this.pageNo = pageNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column answer.ques_id
	 * @return  the value of answer.ques_id
	 * @mbggenerated  Tue Sep 18 00:39:07 CST 2012
	 */
	public Long getQuesId() {
		return quesId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column answer.ques_id
	 * @param quesId  the value for answer.ques_id
	 * @mbggenerated  Tue Sep 18 00:39:07 CST 2012
	 */
	public void setQuesId(Long quesId) {
		this.quesId = quesId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column answer.ques_no
	 * @return  the value of answer.ques_no
	 * @mbggenerated  Tue Sep 18 00:39:07 CST 2012
	 */
	public Integer getQuesNo() {
		return quesNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column answer.ques_no
	 * @param quesNo  the value for answer.ques_no
	 * @mbggenerated  Tue Sep 18 00:39:07 CST 2012
	 */
	public void setQuesNo(Integer quesNo) {
		this.quesNo = quesNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column answer.ques_opt_id
	 * @return  the value of answer.ques_opt_id
	 * @mbggenerated  Tue Sep 18 00:39:07 CST 2012
	 */
	public Long getQuesOptId() {
		return quesOptId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column answer.ques_opt_id
	 * @param quesOptId  the value for answer.ques_opt_id
	 * @mbggenerated  Tue Sep 18 00:39:07 CST 2012
	 */
	public void setQuesOptId(Long quesOptId) {
		this.quesOptId = quesOptId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column answer.ques_opt_no
	 * @return  the value of answer.ques_opt_no
	 * @mbggenerated  Tue Sep 18 00:39:07 CST 2012
	 */
	public Integer getQuesOptNo() {
		return quesOptNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column answer.ques_opt_no
	 * @param quesOptNo  the value for answer.ques_opt_no
	 * @mbggenerated  Tue Sep 18 00:39:07 CST 2012
	 */
	public void setQuesOptNo(Integer quesOptNo) {
		this.quesOptNo = quesOptNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column answer.answer_val
	 * @return  the value of answer.answer_val
	 * @mbggenerated  Tue Sep 18 00:39:07 CST 2012
	 */
	public String getAnswerVal() {
		return answerVal;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column answer.answer_val
	 * @param answerVal  the value for answer.answer_val
	 * @mbggenerated  Tue Sep 18 00:39:07 CST 2012
	 */
	public void setAnswerVal(String answerVal) {
		this.answerVal = answerVal;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column answer.remark
	 * @return  the value of answer.remark
	 * @mbggenerated  Tue Sep 18 00:39:07 CST 2012
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column answer.remark
	 * @param remark  the value for answer.remark
	 * @mbggenerated  Tue Sep 18 00:39:07 CST 2012
	 */
	public void setRemark(String remark) {
		this.remark = remark;
	}
}