package com.survey.panelsns.model.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class AnswerMessExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table answer_mess
	 * @mbggenerated  Tue Sep 18 00:39:07 CST 2012
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table answer_mess
	 * @mbggenerated  Tue Sep 18 00:39:07 CST 2012
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table answer_mess
	 * @mbggenerated  Tue Sep 18 00:39:07 CST 2012
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table answer_mess
	 * @mbggenerated  Tue Sep 18 00:39:07 CST 2012
	 */
	public AnswerMessExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table answer_mess
	 * @mbggenerated  Tue Sep 18 00:39:07 CST 2012
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table answer_mess
	 * @mbggenerated  Tue Sep 18 00:39:07 CST 2012
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table answer_mess
	 * @mbggenerated  Tue Sep 18 00:39:07 CST 2012
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table answer_mess
	 * @mbggenerated  Tue Sep 18 00:39:07 CST 2012
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table answer_mess
	 * @mbggenerated  Tue Sep 18 00:39:07 CST 2012
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table answer_mess
	 * @mbggenerated  Tue Sep 18 00:39:07 CST 2012
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table answer_mess
	 * @mbggenerated  Tue Sep 18 00:39:07 CST 2012
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table answer_mess
	 * @mbggenerated  Tue Sep 18 00:39:07 CST 2012
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table answer_mess
	 * @mbggenerated  Tue Sep 18 00:39:07 CST 2012
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table answer_mess
	 * @mbggenerated  Tue Sep 18 00:39:07 CST 2012
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table answer_mess
	 * @mbggenerated  Tue Sep 18 00:39:07 CST 2012
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		protected void addCriterionForJDBCDate(String condition, Date value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value.getTime()), property);
		}

		protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property + " cannot be null or empty");
			}
			List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
			Iterator<Date> iter = values.iterator();
			while (iter.hasNext()) {
				dateList.add(new java.sql.Date(iter.next().getTime()));
			}
			addCriterion(condition, dateList, property);
		}

		protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Long value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Long value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Long value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Long value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Long value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Long value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Long> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Long> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Long value1, Long value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Long value1, Long value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andNaireIdIsNull() {
			addCriterion("naire_id is null");
			return (Criteria) this;
		}

		public Criteria andNaireIdIsNotNull() {
			addCriterion("naire_id is not null");
			return (Criteria) this;
		}

		public Criteria andNaireIdEqualTo(Long value) {
			addCriterion("naire_id =", value, "naireId");
			return (Criteria) this;
		}

		public Criteria andNaireIdNotEqualTo(Long value) {
			addCriterion("naire_id <>", value, "naireId");
			return (Criteria) this;
		}

		public Criteria andNaireIdGreaterThan(Long value) {
			addCriterion("naire_id >", value, "naireId");
			return (Criteria) this;
		}

		public Criteria andNaireIdGreaterThanOrEqualTo(Long value) {
			addCriterion("naire_id >=", value, "naireId");
			return (Criteria) this;
		}

		public Criteria andNaireIdLessThan(Long value) {
			addCriterion("naire_id <", value, "naireId");
			return (Criteria) this;
		}

		public Criteria andNaireIdLessThanOrEqualTo(Long value) {
			addCriterion("naire_id <=", value, "naireId");
			return (Criteria) this;
		}

		public Criteria andNaireIdIn(List<Long> values) {
			addCriterion("naire_id in", values, "naireId");
			return (Criteria) this;
		}

		public Criteria andNaireIdNotIn(List<Long> values) {
			addCriterion("naire_id not in", values, "naireId");
			return (Criteria) this;
		}

		public Criteria andNaireIdBetween(Long value1, Long value2) {
			addCriterion("naire_id between", value1, value2, "naireId");
			return (Criteria) this;
		}

		public Criteria andNaireIdNotBetween(Long value1, Long value2) {
			addCriterion("naire_id not between", value1, value2, "naireId");
			return (Criteria) this;
		}

		public Criteria andUserIdIsNull() {
			addCriterion("user_id is null");
			return (Criteria) this;
		}

		public Criteria andUserIdIsNotNull() {
			addCriterion("user_id is not null");
			return (Criteria) this;
		}

		public Criteria andUserIdEqualTo(Long value) {
			addCriterion("user_id =", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotEqualTo(Long value) {
			addCriterion("user_id <>", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdGreaterThan(Long value) {
			addCriterion("user_id >", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdGreaterThanOrEqualTo(Long value) {
			addCriterion("user_id >=", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdLessThan(Long value) {
			addCriterion("user_id <", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdLessThanOrEqualTo(Long value) {
			addCriterion("user_id <=", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdIn(List<Long> values) {
			addCriterion("user_id in", values, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotIn(List<Long> values) {
			addCriterion("user_id not in", values, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdBetween(Long value1, Long value2) {
			addCriterion("user_id between", value1, value2, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotBetween(Long value1, Long value2) {
			addCriterion("user_id not between", value1, value2, "userId");
			return (Criteria) this;
		}

		public Criteria andAnswerTimesIsNull() {
			addCriterion("answer_times is null");
			return (Criteria) this;
		}

		public Criteria andAnswerTimesIsNotNull() {
			addCriterion("answer_times is not null");
			return (Criteria) this;
		}

		public Criteria andAnswerTimesEqualTo(Integer value) {
			addCriterion("answer_times =", value, "answerTimes");
			return (Criteria) this;
		}

		public Criteria andAnswerTimesNotEqualTo(Integer value) {
			addCriterion("answer_times <>", value, "answerTimes");
			return (Criteria) this;
		}

		public Criteria andAnswerTimesGreaterThan(Integer value) {
			addCriterion("answer_times >", value, "answerTimes");
			return (Criteria) this;
		}

		public Criteria andAnswerTimesGreaterThanOrEqualTo(Integer value) {
			addCriterion("answer_times >=", value, "answerTimes");
			return (Criteria) this;
		}

		public Criteria andAnswerTimesLessThan(Integer value) {
			addCriterion("answer_times <", value, "answerTimes");
			return (Criteria) this;
		}

		public Criteria andAnswerTimesLessThanOrEqualTo(Integer value) {
			addCriterion("answer_times <=", value, "answerTimes");
			return (Criteria) this;
		}

		public Criteria andAnswerTimesIn(List<Integer> values) {
			addCriterion("answer_times in", values, "answerTimes");
			return (Criteria) this;
		}

		public Criteria andAnswerTimesNotIn(List<Integer> values) {
			addCriterion("answer_times not in", values, "answerTimes");
			return (Criteria) this;
		}

		public Criteria andAnswerTimesBetween(Integer value1, Integer value2) {
			addCriterion("answer_times between", value1, value2, "answerTimes");
			return (Criteria) this;
		}

		public Criteria andAnswerTimesNotBetween(Integer value1, Integer value2) {
			addCriterion("answer_times not between", value1, value2, "answerTimes");
			return (Criteria) this;
		}

		public Criteria andBeginDateIsNull() {
			addCriterion("begin_date is null");
			return (Criteria) this;
		}

		public Criteria andBeginDateIsNotNull() {
			addCriterion("begin_date is not null");
			return (Criteria) this;
		}

		public Criteria andBeginDateEqualTo(Date value) {
			addCriterionForJDBCDate("begin_date =", value, "beginDate");
			return (Criteria) this;
		}

		public Criteria andBeginDateNotEqualTo(Date value) {
			addCriterionForJDBCDate("begin_date <>", value, "beginDate");
			return (Criteria) this;
		}

		public Criteria andBeginDateGreaterThan(Date value) {
			addCriterionForJDBCDate("begin_date >", value, "beginDate");
			return (Criteria) this;
		}

		public Criteria andBeginDateGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("begin_date >=", value, "beginDate");
			return (Criteria) this;
		}

		public Criteria andBeginDateLessThan(Date value) {
			addCriterionForJDBCDate("begin_date <", value, "beginDate");
			return (Criteria) this;
		}

		public Criteria andBeginDateLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("begin_date <=", value, "beginDate");
			return (Criteria) this;
		}

		public Criteria andBeginDateIn(List<Date> values) {
			addCriterionForJDBCDate("begin_date in", values, "beginDate");
			return (Criteria) this;
		}

		public Criteria andBeginDateNotIn(List<Date> values) {
			addCriterionForJDBCDate("begin_date not in", values, "beginDate");
			return (Criteria) this;
		}

		public Criteria andBeginDateBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("begin_date between", value1, value2, "beginDate");
			return (Criteria) this;
		}

		public Criteria andBeginDateNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("begin_date not between", value1, value2, "beginDate");
			return (Criteria) this;
		}

		public Criteria andLastDateIsNull() {
			addCriterion("last_date is null");
			return (Criteria) this;
		}

		public Criteria andLastDateIsNotNull() {
			addCriterion("last_date is not null");
			return (Criteria) this;
		}

		public Criteria andLastDateEqualTo(Date value) {
			addCriterionForJDBCDate("last_date =", value, "lastDate");
			return (Criteria) this;
		}

		public Criteria andLastDateNotEqualTo(Date value) {
			addCriterionForJDBCDate("last_date <>", value, "lastDate");
			return (Criteria) this;
		}

		public Criteria andLastDateGreaterThan(Date value) {
			addCriterionForJDBCDate("last_date >", value, "lastDate");
			return (Criteria) this;
		}

		public Criteria andLastDateGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("last_date >=", value, "lastDate");
			return (Criteria) this;
		}

		public Criteria andLastDateLessThan(Date value) {
			addCriterionForJDBCDate("last_date <", value, "lastDate");
			return (Criteria) this;
		}

		public Criteria andLastDateLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("last_date <=", value, "lastDate");
			return (Criteria) this;
		}

		public Criteria andLastDateIn(List<Date> values) {
			addCriterionForJDBCDate("last_date in", values, "lastDate");
			return (Criteria) this;
		}

		public Criteria andLastDateNotIn(List<Date> values) {
			addCriterionForJDBCDate("last_date not in", values, "lastDate");
			return (Criteria) this;
		}

		public Criteria andLastDateBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("last_date between", value1, value2, "lastDate");
			return (Criteria) this;
		}

		public Criteria andLastDateNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("last_date not between", value1, value2, "lastDate");
			return (Criteria) this;
		}

		public Criteria andEndDateIsNull() {
			addCriterion("end_date is null");
			return (Criteria) this;
		}

		public Criteria andEndDateIsNotNull() {
			addCriterion("end_date is not null");
			return (Criteria) this;
		}

		public Criteria andEndDateEqualTo(Date value) {
			addCriterionForJDBCDate("end_date =", value, "endDate");
			return (Criteria) this;
		}

		public Criteria andEndDateNotEqualTo(Date value) {
			addCriterionForJDBCDate("end_date <>", value, "endDate");
			return (Criteria) this;
		}

		public Criteria andEndDateGreaterThan(Date value) {
			addCriterionForJDBCDate("end_date >", value, "endDate");
			return (Criteria) this;
		}

		public Criteria andEndDateGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("end_date >=", value, "endDate");
			return (Criteria) this;
		}

		public Criteria andEndDateLessThan(Date value) {
			addCriterionForJDBCDate("end_date <", value, "endDate");
			return (Criteria) this;
		}

		public Criteria andEndDateLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("end_date <=", value, "endDate");
			return (Criteria) this;
		}

		public Criteria andEndDateIn(List<Date> values) {
			addCriterionForJDBCDate("end_date in", values, "endDate");
			return (Criteria) this;
		}

		public Criteria andEndDateNotIn(List<Date> values) {
			addCriterionForJDBCDate("end_date not in", values, "endDate");
			return (Criteria) this;
		}

		public Criteria andEndDateBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("end_date between", value1, value2, "endDate");
			return (Criteria) this;
		}

		public Criteria andEndDateNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("end_date not between", value1, value2, "endDate");
			return (Criteria) this;
		}

		public Criteria andStatusIsNull() {
			addCriterion("status is null");
			return (Criteria) this;
		}

		public Criteria andStatusIsNotNull() {
			addCriterion("status is not null");
			return (Criteria) this;
		}

		public Criteria andStatusEqualTo(Integer value) {
			addCriterion("status =", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotEqualTo(Integer value) {
			addCriterion("status <>", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThan(Integer value) {
			addCriterion("status >", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
			addCriterion("status >=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThan(Integer value) {
			addCriterion("status <", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThanOrEqualTo(Integer value) {
			addCriterion("status <=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusIn(List<Integer> values) {
			addCriterion("status in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotIn(List<Integer> values) {
			addCriterion("status not in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusBetween(Integer value1, Integer value2) {
			addCriterion("status between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotBetween(Integer value1, Integer value2) {
			addCriterion("status not between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andInvalidateIsNull() {
			addCriterion("invalidate is null");
			return (Criteria) this;
		}

		public Criteria andInvalidateIsNotNull() {
			addCriterion("invalidate is not null");
			return (Criteria) this;
		}

		public Criteria andInvalidateEqualTo(Integer value) {
			addCriterion("invalidate =", value, "invalidate");
			return (Criteria) this;
		}

		public Criteria andInvalidateNotEqualTo(Integer value) {
			addCriterion("invalidate <>", value, "invalidate");
			return (Criteria) this;
		}

		public Criteria andInvalidateGreaterThan(Integer value) {
			addCriterion("invalidate >", value, "invalidate");
			return (Criteria) this;
		}

		public Criteria andInvalidateGreaterThanOrEqualTo(Integer value) {
			addCriterion("invalidate >=", value, "invalidate");
			return (Criteria) this;
		}

		public Criteria andInvalidateLessThan(Integer value) {
			addCriterion("invalidate <", value, "invalidate");
			return (Criteria) this;
		}

		public Criteria andInvalidateLessThanOrEqualTo(Integer value) {
			addCriterion("invalidate <=", value, "invalidate");
			return (Criteria) this;
		}

		public Criteria andInvalidateIn(List<Integer> values) {
			addCriterion("invalidate in", values, "invalidate");
			return (Criteria) this;
		}

		public Criteria andInvalidateNotIn(List<Integer> values) {
			addCriterion("invalidate not in", values, "invalidate");
			return (Criteria) this;
		}

		public Criteria andInvalidateBetween(Integer value1, Integer value2) {
			addCriterion("invalidate between", value1, value2, "invalidate");
			return (Criteria) this;
		}

		public Criteria andInvalidateNotBetween(Integer value1, Integer value2) {
			addCriterion("invalidate not between", value1, value2, "invalidate");
			return (Criteria) this;
		}

		public Criteria andFirstAnswerIpIsNull() {
			addCriterion("first_answer_ip is null");
			return (Criteria) this;
		}

		public Criteria andFirstAnswerIpIsNotNull() {
			addCriterion("first_answer_ip is not null");
			return (Criteria) this;
		}

		public Criteria andFirstAnswerIpEqualTo(String value) {
			addCriterion("first_answer_ip =", value, "firstAnswerIp");
			return (Criteria) this;
		}

		public Criteria andFirstAnswerIpNotEqualTo(String value) {
			addCriterion("first_answer_ip <>", value, "firstAnswerIp");
			return (Criteria) this;
		}

		public Criteria andFirstAnswerIpGreaterThan(String value) {
			addCriterion("first_answer_ip >", value, "firstAnswerIp");
			return (Criteria) this;
		}

		public Criteria andFirstAnswerIpGreaterThanOrEqualTo(String value) {
			addCriterion("first_answer_ip >=", value, "firstAnswerIp");
			return (Criteria) this;
		}

		public Criteria andFirstAnswerIpLessThan(String value) {
			addCriterion("first_answer_ip <", value, "firstAnswerIp");
			return (Criteria) this;
		}

		public Criteria andFirstAnswerIpLessThanOrEqualTo(String value) {
			addCriterion("first_answer_ip <=", value, "firstAnswerIp");
			return (Criteria) this;
		}

		public Criteria andFirstAnswerIpLike(String value) {
			addCriterion("first_answer_ip like", value, "firstAnswerIp");
			return (Criteria) this;
		}

		public Criteria andFirstAnswerIpNotLike(String value) {
			addCriterion("first_answer_ip not like", value, "firstAnswerIp");
			return (Criteria) this;
		}

		public Criteria andFirstAnswerIpIn(List<String> values) {
			addCriterion("first_answer_ip in", values, "firstAnswerIp");
			return (Criteria) this;
		}

		public Criteria andFirstAnswerIpNotIn(List<String> values) {
			addCriterion("first_answer_ip not in", values, "firstAnswerIp");
			return (Criteria) this;
		}

		public Criteria andFirstAnswerIpBetween(String value1, String value2) {
			addCriterion("first_answer_ip between", value1, value2, "firstAnswerIp");
			return (Criteria) this;
		}

		public Criteria andFirstAnswerIpNotBetween(String value1, String value2) {
			addCriterion("first_answer_ip not between", value1, value2, "firstAnswerIp");
			return (Criteria) this;
		}

		public Criteria andEndAnswerIpIsNull() {
			addCriterion("end_answer_ip is null");
			return (Criteria) this;
		}

		public Criteria andEndAnswerIpIsNotNull() {
			addCriterion("end_answer_ip is not null");
			return (Criteria) this;
		}

		public Criteria andEndAnswerIpEqualTo(String value) {
			addCriterion("end_answer_ip =", value, "endAnswerIp");
			return (Criteria) this;
		}

		public Criteria andEndAnswerIpNotEqualTo(String value) {
			addCriterion("end_answer_ip <>", value, "endAnswerIp");
			return (Criteria) this;
		}

		public Criteria andEndAnswerIpGreaterThan(String value) {
			addCriterion("end_answer_ip >", value, "endAnswerIp");
			return (Criteria) this;
		}

		public Criteria andEndAnswerIpGreaterThanOrEqualTo(String value) {
			addCriterion("end_answer_ip >=", value, "endAnswerIp");
			return (Criteria) this;
		}

		public Criteria andEndAnswerIpLessThan(String value) {
			addCriterion("end_answer_ip <", value, "endAnswerIp");
			return (Criteria) this;
		}

		public Criteria andEndAnswerIpLessThanOrEqualTo(String value) {
			addCriterion("end_answer_ip <=", value, "endAnswerIp");
			return (Criteria) this;
		}

		public Criteria andEndAnswerIpLike(String value) {
			addCriterion("end_answer_ip like", value, "endAnswerIp");
			return (Criteria) this;
		}

		public Criteria andEndAnswerIpNotLike(String value) {
			addCriterion("end_answer_ip not like", value, "endAnswerIp");
			return (Criteria) this;
		}

		public Criteria andEndAnswerIpIn(List<String> values) {
			addCriterion("end_answer_ip in", values, "endAnswerIp");
			return (Criteria) this;
		}

		public Criteria andEndAnswerIpNotIn(List<String> values) {
			addCriterion("end_answer_ip not in", values, "endAnswerIp");
			return (Criteria) this;
		}

		public Criteria andEndAnswerIpBetween(String value1, String value2) {
			addCriterion("end_answer_ip between", value1, value2, "endAnswerIp");
			return (Criteria) this;
		}

		public Criteria andEndAnswerIpNotBetween(String value1, String value2) {
			addCriterion("end_answer_ip not between", value1, value2, "endAnswerIp");
			return (Criteria) this;
		}

		public Criteria andExtInParamsIsNull() {
			addCriterion("ext_in_params is null");
			return (Criteria) this;
		}

		public Criteria andExtInParamsIsNotNull() {
			addCriterion("ext_in_params is not null");
			return (Criteria) this;
		}

		public Criteria andExtInParamsEqualTo(String value) {
			addCriterion("ext_in_params =", value, "extInParams");
			return (Criteria) this;
		}

		public Criteria andExtInParamsNotEqualTo(String value) {
			addCriterion("ext_in_params <>", value, "extInParams");
			return (Criteria) this;
		}

		public Criteria andExtInParamsGreaterThan(String value) {
			addCriterion("ext_in_params >", value, "extInParams");
			return (Criteria) this;
		}

		public Criteria andExtInParamsGreaterThanOrEqualTo(String value) {
			addCriterion("ext_in_params >=", value, "extInParams");
			return (Criteria) this;
		}

		public Criteria andExtInParamsLessThan(String value) {
			addCriterion("ext_in_params <", value, "extInParams");
			return (Criteria) this;
		}

		public Criteria andExtInParamsLessThanOrEqualTo(String value) {
			addCriterion("ext_in_params <=", value, "extInParams");
			return (Criteria) this;
		}

		public Criteria andExtInParamsLike(String value) {
			addCriterion("ext_in_params like", value, "extInParams");
			return (Criteria) this;
		}

		public Criteria andExtInParamsNotLike(String value) {
			addCriterion("ext_in_params not like", value, "extInParams");
			return (Criteria) this;
		}

		public Criteria andExtInParamsIn(List<String> values) {
			addCriterion("ext_in_params in", values, "extInParams");
			return (Criteria) this;
		}

		public Criteria andExtInParamsNotIn(List<String> values) {
			addCriterion("ext_in_params not in", values, "extInParams");
			return (Criteria) this;
		}

		public Criteria andExtInParamsBetween(String value1, String value2) {
			addCriterion("ext_in_params between", value1, value2, "extInParams");
			return (Criteria) this;
		}

		public Criteria andExtInParamsNotBetween(String value1, String value2) {
			addCriterion("ext_in_params not between", value1, value2, "extInParams");
			return (Criteria) this;
		}

		public Criteria andVersionIsNull() {
			addCriterion("version is null");
			return (Criteria) this;
		}

		public Criteria andVersionIsNotNull() {
			addCriterion("version is not null");
			return (Criteria) this;
		}

		public Criteria andVersionEqualTo(Integer value) {
			addCriterion("version =", value, "version");
			return (Criteria) this;
		}

		public Criteria andVersionNotEqualTo(Integer value) {
			addCriterion("version <>", value, "version");
			return (Criteria) this;
		}

		public Criteria andVersionGreaterThan(Integer value) {
			addCriterion("version >", value, "version");
			return (Criteria) this;
		}

		public Criteria andVersionGreaterThanOrEqualTo(Integer value) {
			addCriterion("version >=", value, "version");
			return (Criteria) this;
		}

		public Criteria andVersionLessThan(Integer value) {
			addCriterion("version <", value, "version");
			return (Criteria) this;
		}

		public Criteria andVersionLessThanOrEqualTo(Integer value) {
			addCriterion("version <=", value, "version");
			return (Criteria) this;
		}

		public Criteria andVersionIn(List<Integer> values) {
			addCriterion("version in", values, "version");
			return (Criteria) this;
		}

		public Criteria andVersionNotIn(List<Integer> values) {
			addCriterion("version not in", values, "version");
			return (Criteria) this;
		}

		public Criteria andVersionBetween(Integer value1, Integer value2) {
			addCriterion("version between", value1, value2, "version");
			return (Criteria) this;
		}

		public Criteria andVersionNotBetween(Integer value1, Integer value2) {
			addCriterion("version not between", value1, value2, "version");
			return (Criteria) this;
		}

		public Criteria andRemarkIsNull() {
			addCriterion("remark is null");
			return (Criteria) this;
		}

		public Criteria andRemarkIsNotNull() {
			addCriterion("remark is not null");
			return (Criteria) this;
		}

		public Criteria andRemarkEqualTo(String value) {
			addCriterion("remark =", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkNotEqualTo(String value) {
			addCriterion("remark <>", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkGreaterThan(String value) {
			addCriterion("remark >", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkGreaterThanOrEqualTo(String value) {
			addCriterion("remark >=", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkLessThan(String value) {
			addCriterion("remark <", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkLessThanOrEqualTo(String value) {
			addCriterion("remark <=", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkLike(String value) {
			addCriterion("remark like", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkNotLike(String value) {
			addCriterion("remark not like", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkIn(List<String> values) {
			addCriterion("remark in", values, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkNotIn(List<String> values) {
			addCriterion("remark not in", values, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkBetween(String value1, String value2) {
			addCriterion("remark between", value1, value2, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkNotBetween(String value1, String value2) {
			addCriterion("remark not between", value1, value2, "remark");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table answer_mess
	 * @mbggenerated  Tue Sep 18 00:39:07 CST 2012
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table answer_mess
     *
     * @mbggenerated do_not_delete_during_merge Mon Sep 17 23:07:17 CST 2012
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}