package com.survey.panelsns.model.entity;

import java.util.ArrayList;
import java.util.List;

public class AnswerExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table answer
     *
     * @mbggenerated Mon Sep 17 23:07:17 CST 2012
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table answer
     *
     * @mbggenerated Mon Sep 17 23:07:17 CST 2012
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table answer
     *
     * @mbggenerated Mon Sep 17 23:07:17 CST 2012
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table answer
     *
     * @mbggenerated Mon Sep 17 23:07:17 CST 2012
     */
    public AnswerExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table answer
     *
     * @mbggenerated Mon Sep 17 23:07:17 CST 2012
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table answer
     *
     * @mbggenerated Mon Sep 17 23:07:17 CST 2012
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table answer
     *
     * @mbggenerated Mon Sep 17 23:07:17 CST 2012
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table answer
     *
     * @mbggenerated Mon Sep 17 23:07:17 CST 2012
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table answer
     *
     * @mbggenerated Mon Sep 17 23:07:17 CST 2012
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table answer
     *
     * @mbggenerated Mon Sep 17 23:07:17 CST 2012
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table answer
     *
     * @mbggenerated Mon Sep 17 23:07:17 CST 2012
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table answer
     *
     * @mbggenerated Mon Sep 17 23:07:17 CST 2012
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table answer
     *
     * @mbggenerated Mon Sep 17 23:07:17 CST 2012
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table answer
     *
     * @mbggenerated Mon Sep 17 23:07:17 CST 2012
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table answer
     *
     * @mbggenerated Mon Sep 17 23:07:17 CST 2012
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andAnswerMessIdIsNull() {
            addCriterion("answer_mess_id is null");
            return (Criteria) this;
        }

        public Criteria andAnswerMessIdIsNotNull() {
            addCriterion("answer_mess_id is not null");
            return (Criteria) this;
        }

        public Criteria andAnswerMessIdEqualTo(Long value) {
            addCriterion("answer_mess_id =", value, "answerMessId");
            return (Criteria) this;
        }

        public Criteria andAnswerMessIdNotEqualTo(Long value) {
            addCriterion("answer_mess_id <>", value, "answerMessId");
            return (Criteria) this;
        }

        public Criteria andAnswerMessIdGreaterThan(Long value) {
            addCriterion("answer_mess_id >", value, "answerMessId");
            return (Criteria) this;
        }

        public Criteria andAnswerMessIdGreaterThanOrEqualTo(Long value) {
            addCriterion("answer_mess_id >=", value, "answerMessId");
            return (Criteria) this;
        }

        public Criteria andAnswerMessIdLessThan(Long value) {
            addCriterion("answer_mess_id <", value, "answerMessId");
            return (Criteria) this;
        }

        public Criteria andAnswerMessIdLessThanOrEqualTo(Long value) {
            addCriterion("answer_mess_id <=", value, "answerMessId");
            return (Criteria) this;
        }

        public Criteria andAnswerMessIdIn(List<Long> values) {
            addCriterion("answer_mess_id in", values, "answerMessId");
            return (Criteria) this;
        }

        public Criteria andAnswerMessIdNotIn(List<Long> values) {
            addCriterion("answer_mess_id not in", values, "answerMessId");
            return (Criteria) this;
        }

        public Criteria andAnswerMessIdBetween(Long value1, Long value2) {
            addCriterion("answer_mess_id between", value1, value2, "answerMessId");
            return (Criteria) this;
        }

        public Criteria andAnswerMessIdNotBetween(Long value1, Long value2) {
            addCriterion("answer_mess_id not between", value1, value2, "answerMessId");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(Long value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(Long value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(Long value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Long value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(Long value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Long value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<Long> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<Long> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(Long value1, Long value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(Long value1, Long value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andNaireIdIsNull() {
            addCriterion("naire_id is null");
            return (Criteria) this;
        }

        public Criteria andNaireIdIsNotNull() {
            addCriterion("naire_id is not null");
            return (Criteria) this;
        }

        public Criteria andNaireIdEqualTo(Long value) {
            addCriterion("naire_id =", value, "naireId");
            return (Criteria) this;
        }

        public Criteria andNaireIdNotEqualTo(Long value) {
            addCriterion("naire_id <>", value, "naireId");
            return (Criteria) this;
        }

        public Criteria andNaireIdGreaterThan(Long value) {
            addCriterion("naire_id >", value, "naireId");
            return (Criteria) this;
        }

        public Criteria andNaireIdGreaterThanOrEqualTo(Long value) {
            addCriterion("naire_id >=", value, "naireId");
            return (Criteria) this;
        }

        public Criteria andNaireIdLessThan(Long value) {
            addCriterion("naire_id <", value, "naireId");
            return (Criteria) this;
        }

        public Criteria andNaireIdLessThanOrEqualTo(Long value) {
            addCriterion("naire_id <=", value, "naireId");
            return (Criteria) this;
        }

        public Criteria andNaireIdIn(List<Long> values) {
            addCriterion("naire_id in", values, "naireId");
            return (Criteria) this;
        }

        public Criteria andNaireIdNotIn(List<Long> values) {
            addCriterion("naire_id not in", values, "naireId");
            return (Criteria) this;
        }

        public Criteria andNaireIdBetween(Long value1, Long value2) {
            addCriterion("naire_id between", value1, value2, "naireId");
            return (Criteria) this;
        }

        public Criteria andNaireIdNotBetween(Long value1, Long value2) {
            addCriterion("naire_id not between", value1, value2, "naireId");
            return (Criteria) this;
        }

        public Criteria andPageNoIsNull() {
            addCriterion("page_no is null");
            return (Criteria) this;
        }

        public Criteria andPageNoIsNotNull() {
            addCriterion("page_no is not null");
            return (Criteria) this;
        }

        public Criteria andPageNoEqualTo(Integer value) {
            addCriterion("page_no =", value, "pageNo");
            return (Criteria) this;
        }

        public Criteria andPageNoNotEqualTo(Integer value) {
            addCriterion("page_no <>", value, "pageNo");
            return (Criteria) this;
        }

        public Criteria andPageNoGreaterThan(Integer value) {
            addCriterion("page_no >", value, "pageNo");
            return (Criteria) this;
        }

        public Criteria andPageNoGreaterThanOrEqualTo(Integer value) {
            addCriterion("page_no >=", value, "pageNo");
            return (Criteria) this;
        }

        public Criteria andPageNoLessThan(Integer value) {
            addCriterion("page_no <", value, "pageNo");
            return (Criteria) this;
        }

        public Criteria andPageNoLessThanOrEqualTo(Integer value) {
            addCriterion("page_no <=", value, "pageNo");
            return (Criteria) this;
        }

        public Criteria andPageNoIn(List<Integer> values) {
            addCriterion("page_no in", values, "pageNo");
            return (Criteria) this;
        }

        public Criteria andPageNoNotIn(List<Integer> values) {
            addCriterion("page_no not in", values, "pageNo");
            return (Criteria) this;
        }

        public Criteria andPageNoBetween(Integer value1, Integer value2) {
            addCriterion("page_no between", value1, value2, "pageNo");
            return (Criteria) this;
        }

        public Criteria andPageNoNotBetween(Integer value1, Integer value2) {
            addCriterion("page_no not between", value1, value2, "pageNo");
            return (Criteria) this;
        }

        public Criteria andQuesIdIsNull() {
            addCriterion("ques_id is null");
            return (Criteria) this;
        }

        public Criteria andQuesIdIsNotNull() {
            addCriterion("ques_id is not null");
            return (Criteria) this;
        }

        public Criteria andQuesIdEqualTo(Long value) {
            addCriterion("ques_id =", value, "quesId");
            return (Criteria) this;
        }

        public Criteria andQuesIdNotEqualTo(Long value) {
            addCriterion("ques_id <>", value, "quesId");
            return (Criteria) this;
        }

        public Criteria andQuesIdGreaterThan(Long value) {
            addCriterion("ques_id >", value, "quesId");
            return (Criteria) this;
        }

        public Criteria andQuesIdGreaterThanOrEqualTo(Long value) {
            addCriterion("ques_id >=", value, "quesId");
            return (Criteria) this;
        }

        public Criteria andQuesIdLessThan(Long value) {
            addCriterion("ques_id <", value, "quesId");
            return (Criteria) this;
        }

        public Criteria andQuesIdLessThanOrEqualTo(Long value) {
            addCriterion("ques_id <=", value, "quesId");
            return (Criteria) this;
        }

        public Criteria andQuesIdIn(List<Long> values) {
            addCriterion("ques_id in", values, "quesId");
            return (Criteria) this;
        }

        public Criteria andQuesIdNotIn(List<Long> values) {
            addCriterion("ques_id not in", values, "quesId");
            return (Criteria) this;
        }

        public Criteria andQuesIdBetween(Long value1, Long value2) {
            addCriterion("ques_id between", value1, value2, "quesId");
            return (Criteria) this;
        }

        public Criteria andQuesIdNotBetween(Long value1, Long value2) {
            addCriterion("ques_id not between", value1, value2, "quesId");
            return (Criteria) this;
        }

        public Criteria andQuesNoIsNull() {
            addCriterion("ques_no is null");
            return (Criteria) this;
        }

        public Criteria andQuesNoIsNotNull() {
            addCriterion("ques_no is not null");
            return (Criteria) this;
        }

        public Criteria andQuesNoEqualTo(Integer value) {
            addCriterion("ques_no =", value, "quesNo");
            return (Criteria) this;
        }

        public Criteria andQuesNoNotEqualTo(Integer value) {
            addCriterion("ques_no <>", value, "quesNo");
            return (Criteria) this;
        }

        public Criteria andQuesNoGreaterThan(Integer value) {
            addCriterion("ques_no >", value, "quesNo");
            return (Criteria) this;
        }

        public Criteria andQuesNoGreaterThanOrEqualTo(Integer value) {
            addCriterion("ques_no >=", value, "quesNo");
            return (Criteria) this;
        }

        public Criteria andQuesNoLessThan(Integer value) {
            addCriterion("ques_no <", value, "quesNo");
            return (Criteria) this;
        }

        public Criteria andQuesNoLessThanOrEqualTo(Integer value) {
            addCriterion("ques_no <=", value, "quesNo");
            return (Criteria) this;
        }

        public Criteria andQuesNoIn(List<Integer> values) {
            addCriterion("ques_no in", values, "quesNo");
            return (Criteria) this;
        }

        public Criteria andQuesNoNotIn(List<Integer> values) {
            addCriterion("ques_no not in", values, "quesNo");
            return (Criteria) this;
        }

        public Criteria andQuesNoBetween(Integer value1, Integer value2) {
            addCriterion("ques_no between", value1, value2, "quesNo");
            return (Criteria) this;
        }

        public Criteria andQuesNoNotBetween(Integer value1, Integer value2) {
            addCriterion("ques_no not between", value1, value2, "quesNo");
            return (Criteria) this;
        }

        public Criteria andQuesOptIdIsNull() {
            addCriterion("ques_opt_id is null");
            return (Criteria) this;
        }

        public Criteria andQuesOptIdIsNotNull() {
            addCriterion("ques_opt_id is not null");
            return (Criteria) this;
        }

        public Criteria andQuesOptIdEqualTo(Long value) {
            addCriterion("ques_opt_id =", value, "quesOptId");
            return (Criteria) this;
        }

        public Criteria andQuesOptIdNotEqualTo(Long value) {
            addCriterion("ques_opt_id <>", value, "quesOptId");
            return (Criteria) this;
        }

        public Criteria andQuesOptIdGreaterThan(Long value) {
            addCriterion("ques_opt_id >", value, "quesOptId");
            return (Criteria) this;
        }

        public Criteria andQuesOptIdGreaterThanOrEqualTo(Long value) {
            addCriterion("ques_opt_id >=", value, "quesOptId");
            return (Criteria) this;
        }

        public Criteria andQuesOptIdLessThan(Long value) {
            addCriterion("ques_opt_id <", value, "quesOptId");
            return (Criteria) this;
        }

        public Criteria andQuesOptIdLessThanOrEqualTo(Long value) {
            addCriterion("ques_opt_id <=", value, "quesOptId");
            return (Criteria) this;
        }

        public Criteria andQuesOptIdIn(List<Long> values) {
            addCriterion("ques_opt_id in", values, "quesOptId");
            return (Criteria) this;
        }

        public Criteria andQuesOptIdNotIn(List<Long> values) {
            addCriterion("ques_opt_id not in", values, "quesOptId");
            return (Criteria) this;
        }

        public Criteria andQuesOptIdBetween(Long value1, Long value2) {
            addCriterion("ques_opt_id between", value1, value2, "quesOptId");
            return (Criteria) this;
        }

        public Criteria andQuesOptIdNotBetween(Long value1, Long value2) {
            addCriterion("ques_opt_id not between", value1, value2, "quesOptId");
            return (Criteria) this;
        }

        public Criteria andQuesOptNoIsNull() {
            addCriterion("ques_opt_no is null");
            return (Criteria) this;
        }

        public Criteria andQuesOptNoIsNotNull() {
            addCriterion("ques_opt_no is not null");
            return (Criteria) this;
        }

        public Criteria andQuesOptNoEqualTo(Integer value) {
            addCriterion("ques_opt_no =", value, "quesOptNo");
            return (Criteria) this;
        }

        public Criteria andQuesOptNoNotEqualTo(Integer value) {
            addCriterion("ques_opt_no <>", value, "quesOptNo");
            return (Criteria) this;
        }

        public Criteria andQuesOptNoGreaterThan(Integer value) {
            addCriterion("ques_opt_no >", value, "quesOptNo");
            return (Criteria) this;
        }

        public Criteria andQuesOptNoGreaterThanOrEqualTo(Integer value) {
            addCriterion("ques_opt_no >=", value, "quesOptNo");
            return (Criteria) this;
        }

        public Criteria andQuesOptNoLessThan(Integer value) {
            addCriterion("ques_opt_no <", value, "quesOptNo");
            return (Criteria) this;
        }

        public Criteria andQuesOptNoLessThanOrEqualTo(Integer value) {
            addCriterion("ques_opt_no <=", value, "quesOptNo");
            return (Criteria) this;
        }

        public Criteria andQuesOptNoIn(List<Integer> values) {
            addCriterion("ques_opt_no in", values, "quesOptNo");
            return (Criteria) this;
        }

        public Criteria andQuesOptNoNotIn(List<Integer> values) {
            addCriterion("ques_opt_no not in", values, "quesOptNo");
            return (Criteria) this;
        }

        public Criteria andQuesOptNoBetween(Integer value1, Integer value2) {
            addCriterion("ques_opt_no between", value1, value2, "quesOptNo");
            return (Criteria) this;
        }

        public Criteria andQuesOptNoNotBetween(Integer value1, Integer value2) {
            addCriterion("ques_opt_no not between", value1, value2, "quesOptNo");
            return (Criteria) this;
        }

        public Criteria andAnswerValIsNull() {
            addCriterion("answer_val is null");
            return (Criteria) this;
        }

        public Criteria andAnswerValIsNotNull() {
            addCriterion("answer_val is not null");
            return (Criteria) this;
        }

        public Criteria andAnswerValEqualTo(String value) {
            addCriterion("answer_val =", value, "answerVal");
            return (Criteria) this;
        }

        public Criteria andAnswerValNotEqualTo(String value) {
            addCriterion("answer_val <>", value, "answerVal");
            return (Criteria) this;
        }

        public Criteria andAnswerValGreaterThan(String value) {
            addCriterion("answer_val >", value, "answerVal");
            return (Criteria) this;
        }

        public Criteria andAnswerValGreaterThanOrEqualTo(String value) {
            addCriterion("answer_val >=", value, "answerVal");
            return (Criteria) this;
        }

        public Criteria andAnswerValLessThan(String value) {
            addCriterion("answer_val <", value, "answerVal");
            return (Criteria) this;
        }

        public Criteria andAnswerValLessThanOrEqualTo(String value) {
            addCriterion("answer_val <=", value, "answerVal");
            return (Criteria) this;
        }

        public Criteria andAnswerValLike(String value) {
            addCriterion("answer_val like", value, "answerVal");
            return (Criteria) this;
        }

        public Criteria andAnswerValNotLike(String value) {
            addCriterion("answer_val not like", value, "answerVal");
            return (Criteria) this;
        }

        public Criteria andAnswerValIn(List<String> values) {
            addCriterion("answer_val in", values, "answerVal");
            return (Criteria) this;
        }

        public Criteria andAnswerValNotIn(List<String> values) {
            addCriterion("answer_val not in", values, "answerVal");
            return (Criteria) this;
        }

        public Criteria andAnswerValBetween(String value1, String value2) {
            addCriterion("answer_val between", value1, value2, "answerVal");
            return (Criteria) this;
        }

        public Criteria andAnswerValNotBetween(String value1, String value2) {
            addCriterion("answer_val not between", value1, value2, "answerVal");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("remark is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("remark is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("remark =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("remark <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("remark >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("remark >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("remark <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("remark <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("remark like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("remark not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("remark in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("remark not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("remark between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("remark not between", value1, value2, "remark");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table answer
     *
     * @mbggenerated do_not_delete_during_merge Mon Sep 17 23:07:17 CST 2012
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table answer
     *
     * @mbggenerated Mon Sep 17 23:07:17 CST 2012
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}