package com.survey.panelsns.model.entity;

public class Logic {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column logic.id
	 * @mbggenerated  Mon Sep 17 23:07:17 CST 2012
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column logic.ques_naire_id
	 * @mbggenerated  Mon Sep 17 23:07:17 CST 2012
	 */
	private Long quesNaireId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column logic.ques_id
	 * @mbggenerated  Mon Sep 17 23:07:17 CST 2012
	 */
	private Long quesId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column logic.ques_option_id
	 * @mbggenerated  Mon Sep 17 23:07:17 CST 2012
	 */
	private Long quesOptionId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column logic.type
	 * @mbggenerated  Mon Sep 17 23:07:17 CST 2012
	 */
	private Integer type;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column logic.ctl_type
	 * @mbggenerated  Mon Sep 17 23:07:17 CST 2012
	 */
	private Integer ctlType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column logic.out_type
	 * @mbggenerated  Mon Sep 17 23:07:17 CST 2012
	 */
	private Integer outType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column logic.out_value
	 * @mbggenerated  Mon Sep 17 23:07:17 CST 2012
	 */
	private Integer outValue;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column logic.version
	 * @mbggenerated  Mon Sep 17 23:07:17 CST 2012
	 */
	private Integer version;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column logic.remark
	 * @mbggenerated  Mon Sep 17 23:07:17 CST 2012
	 */
	private String remark;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column logic.id
	 * @return  the value of logic.id
	 * @mbggenerated  Mon Sep 17 23:07:17 CST 2012
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column logic.id
	 * @param id  the value for logic.id
	 * @mbggenerated  Mon Sep 17 23:07:17 CST 2012
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column logic.ques_naire_id
	 * @return  the value of logic.ques_naire_id
	 * @mbggenerated  Mon Sep 17 23:07:17 CST 2012
	 */
	public Long getQuesNaireId() {
		return quesNaireId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column logic.ques_naire_id
	 * @param quesNaireId  the value for logic.ques_naire_id
	 * @mbggenerated  Mon Sep 17 23:07:17 CST 2012
	 */
	public void setQuesNaireId(Long quesNaireId) {
		this.quesNaireId = quesNaireId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column logic.ques_id
	 * @return  the value of logic.ques_id
	 * @mbggenerated  Mon Sep 17 23:07:17 CST 2012
	 */
	public Long getQuesId() {
		return quesId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column logic.ques_id
	 * @param quesId  the value for logic.ques_id
	 * @mbggenerated  Mon Sep 17 23:07:17 CST 2012
	 */
	public void setQuesId(Long quesId) {
		this.quesId = quesId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column logic.ques_option_id
	 * @return  the value of logic.ques_option_id
	 * @mbggenerated  Mon Sep 17 23:07:17 CST 2012
	 */
	public Long getQuesOptionId() {
		return quesOptionId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column logic.ques_option_id
	 * @param quesOptionId  the value for logic.ques_option_id
	 * @mbggenerated  Mon Sep 17 23:07:17 CST 2012
	 */
	public void setQuesOptionId(Long quesOptionId) {
		this.quesOptionId = quesOptionId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column logic.type
	 * @return  the value of logic.type
	 * @mbggenerated  Mon Sep 17 23:07:17 CST 2012
	 */
	public Integer getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column logic.type
	 * @param type  the value for logic.type
	 * @mbggenerated  Mon Sep 17 23:07:17 CST 2012
	 */
	public void setType(Integer type) {
		this.type = type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column logic.ctl_type
	 * @return  the value of logic.ctl_type
	 * @mbggenerated  Mon Sep 17 23:07:17 CST 2012
	 */
	public Integer getCtlType() {
		return ctlType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column logic.ctl_type
	 * @param ctlType  the value for logic.ctl_type
	 * @mbggenerated  Mon Sep 17 23:07:17 CST 2012
	 */
	public void setCtlType(Integer ctlType) {
		this.ctlType = ctlType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column logic.out_type
	 * @return  the value of logic.out_type
	 * @mbggenerated  Mon Sep 17 23:07:17 CST 2012
	 */
	public Integer getOutType() {
		return outType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column logic.out_type
	 * @param outType  the value for logic.out_type
	 * @mbggenerated  Mon Sep 17 23:07:17 CST 2012
	 */
	public void setOutType(Integer outType) {
		this.outType = outType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column logic.out_value
	 * @return  the value of logic.out_value
	 * @mbggenerated  Mon Sep 17 23:07:17 CST 2012
	 */
	public Integer getOutValue() {
		return outValue;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column logic.out_value
	 * @param outValue  the value for logic.out_value
	 * @mbggenerated  Mon Sep 17 23:07:17 CST 2012
	 */
	public void setOutValue(Integer outValue) {
		this.outValue = outValue;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column logic.version
	 * @return  the value of logic.version
	 * @mbggenerated  Mon Sep 17 23:07:17 CST 2012
	 */
	public Integer getVersion() {
		return version;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column logic.version
	 * @param version  the value for logic.version
	 * @mbggenerated  Mon Sep 17 23:07:17 CST 2012
	 */
	public void setVersion(Integer version) {
		this.version = version;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column logic.remark
	 * @return  the value of logic.remark
	 * @mbggenerated  Mon Sep 17 23:07:17 CST 2012
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column logic.remark
	 * @param remark  the value for logic.remark
	 * @mbggenerated  Mon Sep 17 23:07:17 CST 2012
	 */
	public void setRemark(String remark) {
		this.remark = remark;
	}
}