package com.survey.panelsns.model.entity;

import java.util.ArrayList;
import java.util.List;

public class LogicExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table logic
	 * @mbggenerated  Sat Aug 25 14:14:03 CST 2012
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table logic
	 * @mbggenerated  Sat Aug 25 14:14:03 CST 2012
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table logic
	 * @mbggenerated  Sat Aug 25 14:14:03 CST 2012
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table logic
	 * @mbggenerated  Sat Aug 25 14:14:03 CST 2012
	 */
	public LogicExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table logic
	 * @mbggenerated  Sat Aug 25 14:14:03 CST 2012
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table logic
	 * @mbggenerated  Sat Aug 25 14:14:03 CST 2012
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table logic
	 * @mbggenerated  Sat Aug 25 14:14:03 CST 2012
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table logic
	 * @mbggenerated  Sat Aug 25 14:14:03 CST 2012
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table logic
	 * @mbggenerated  Sat Aug 25 14:14:03 CST 2012
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table logic
	 * @mbggenerated  Sat Aug 25 14:14:03 CST 2012
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table logic
	 * @mbggenerated  Sat Aug 25 14:14:03 CST 2012
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table logic
	 * @mbggenerated  Sat Aug 25 14:14:03 CST 2012
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table logic
	 * @mbggenerated  Sat Aug 25 14:14:03 CST 2012
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table logic
	 * @mbggenerated  Sat Aug 25 14:14:03 CST 2012
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table logic
	 * @mbggenerated  Sat Aug 25 14:14:03 CST 2012
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Long value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Long value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Long value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Long value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Long value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Long value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Long> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Long> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Long value1, Long value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Long value1, Long value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andQuesNaireIdIsNull() {
			addCriterion("ques_naire_id is null");
			return (Criteria) this;
		}

		public Criteria andQuesNaireIdIsNotNull() {
			addCriterion("ques_naire_id is not null");
			return (Criteria) this;
		}

		public Criteria andQuesNaireIdEqualTo(Long value) {
			addCriterion("ques_naire_id =", value, "quesNaireId");
			return (Criteria) this;
		}

		public Criteria andQuesNaireIdNotEqualTo(Long value) {
			addCriterion("ques_naire_id <>", value, "quesNaireId");
			return (Criteria) this;
		}

		public Criteria andQuesNaireIdGreaterThan(Long value) {
			addCriterion("ques_naire_id >", value, "quesNaireId");
			return (Criteria) this;
		}

		public Criteria andQuesNaireIdGreaterThanOrEqualTo(Long value) {
			addCriterion("ques_naire_id >=", value, "quesNaireId");
			return (Criteria) this;
		}

		public Criteria andQuesNaireIdLessThan(Long value) {
			addCriterion("ques_naire_id <", value, "quesNaireId");
			return (Criteria) this;
		}

		public Criteria andQuesNaireIdLessThanOrEqualTo(Long value) {
			addCriterion("ques_naire_id <=", value, "quesNaireId");
			return (Criteria) this;
		}

		public Criteria andQuesNaireIdIn(List<Long> values) {
			addCriterion("ques_naire_id in", values, "quesNaireId");
			return (Criteria) this;
		}

		public Criteria andQuesNaireIdNotIn(List<Long> values) {
			addCriterion("ques_naire_id not in", values, "quesNaireId");
			return (Criteria) this;
		}

		public Criteria andQuesNaireIdBetween(Long value1, Long value2) {
			addCriterion("ques_naire_id between", value1, value2, "quesNaireId");
			return (Criteria) this;
		}

		public Criteria andQuesNaireIdNotBetween(Long value1, Long value2) {
			addCriterion("ques_naire_id not between", value1, value2,
					"quesNaireId");
			return (Criteria) this;
		}

		public Criteria andQuesIdIsNull() {
			addCriterion("ques_id is null");
			return (Criteria) this;
		}

		public Criteria andQuesIdIsNotNull() {
			addCriterion("ques_id is not null");
			return (Criteria) this;
		}

		public Criteria andQuesIdEqualTo(Long value) {
			addCriterion("ques_id =", value, "quesId");
			return (Criteria) this;
		}

		public Criteria andQuesIdNotEqualTo(Long value) {
			addCriterion("ques_id <>", value, "quesId");
			return (Criteria) this;
		}

		public Criteria andQuesIdGreaterThan(Long value) {
			addCriterion("ques_id >", value, "quesId");
			return (Criteria) this;
		}

		public Criteria andQuesIdGreaterThanOrEqualTo(Long value) {
			addCriterion("ques_id >=", value, "quesId");
			return (Criteria) this;
		}

		public Criteria andQuesIdLessThan(Long value) {
			addCriterion("ques_id <", value, "quesId");
			return (Criteria) this;
		}

		public Criteria andQuesIdLessThanOrEqualTo(Long value) {
			addCriterion("ques_id <=", value, "quesId");
			return (Criteria) this;
		}

		public Criteria andQuesIdIn(List<Long> values) {
			addCriterion("ques_id in", values, "quesId");
			return (Criteria) this;
		}

		public Criteria andQuesIdNotIn(List<Long> values) {
			addCriterion("ques_id not in", values, "quesId");
			return (Criteria) this;
		}

		public Criteria andQuesIdBetween(Long value1, Long value2) {
			addCriterion("ques_id between", value1, value2, "quesId");
			return (Criteria) this;
		}

		public Criteria andQuesIdNotBetween(Long value1, Long value2) {
			addCriterion("ques_id not between", value1, value2, "quesId");
			return (Criteria) this;
		}

		public Criteria andQuesOptionIdIsNull() {
			addCriterion("ques_option_id is null");
			return (Criteria) this;
		}

		public Criteria andQuesOptionIdIsNotNull() {
			addCriterion("ques_option_id is not null");
			return (Criteria) this;
		}

		public Criteria andQuesOptionIdEqualTo(Long value) {
			addCriterion("ques_option_id =", value, "quesOptionId");
			return (Criteria) this;
		}

		public Criteria andQuesOptionIdNotEqualTo(Long value) {
			addCriterion("ques_option_id <>", value, "quesOptionId");
			return (Criteria) this;
		}

		public Criteria andQuesOptionIdGreaterThan(Long value) {
			addCriterion("ques_option_id >", value, "quesOptionId");
			return (Criteria) this;
		}

		public Criteria andQuesOptionIdGreaterThanOrEqualTo(Long value) {
			addCriterion("ques_option_id >=", value, "quesOptionId");
			return (Criteria) this;
		}

		public Criteria andQuesOptionIdLessThan(Long value) {
			addCriterion("ques_option_id <", value, "quesOptionId");
			return (Criteria) this;
		}

		public Criteria andQuesOptionIdLessThanOrEqualTo(Long value) {
			addCriterion("ques_option_id <=", value, "quesOptionId");
			return (Criteria) this;
		}

		public Criteria andQuesOptionIdIn(List<Long> values) {
			addCriterion("ques_option_id in", values, "quesOptionId");
			return (Criteria) this;
		}

		public Criteria andQuesOptionIdNotIn(List<Long> values) {
			addCriterion("ques_option_id not in", values, "quesOptionId");
			return (Criteria) this;
		}

		public Criteria andQuesOptionIdBetween(Long value1, Long value2) {
			addCriterion("ques_option_id between", value1, value2,
					"quesOptionId");
			return (Criteria) this;
		}

		public Criteria andQuesOptionIdNotBetween(Long value1, Long value2) {
			addCriterion("ques_option_id not between", value1, value2,
					"quesOptionId");
			return (Criteria) this;
		}

		public Criteria andTypeIsNull() {
			addCriterion("type is null");
			return (Criteria) this;
		}

		public Criteria andTypeIsNotNull() {
			addCriterion("type is not null");
			return (Criteria) this;
		}

		public Criteria andTypeEqualTo(Integer value) {
			addCriterion("type =", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeNotEqualTo(Integer value) {
			addCriterion("type <>", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeGreaterThan(Integer value) {
			addCriterion("type >", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeGreaterThanOrEqualTo(Integer value) {
			addCriterion("type >=", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeLessThan(Integer value) {
			addCriterion("type <", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeLessThanOrEqualTo(Integer value) {
			addCriterion("type <=", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeIn(List<Integer> values) {
			addCriterion("type in", values, "type");
			return (Criteria) this;
		}

		public Criteria andTypeNotIn(List<Integer> values) {
			addCriterion("type not in", values, "type");
			return (Criteria) this;
		}

		public Criteria andTypeBetween(Integer value1, Integer value2) {
			addCriterion("type between", value1, value2, "type");
			return (Criteria) this;
		}

		public Criteria andTypeNotBetween(Integer value1, Integer value2) {
			addCriterion("type not between", value1, value2, "type");
			return (Criteria) this;
		}

		public Criteria andCtlTypeIsNull() {
			addCriterion("ctl_type is null");
			return (Criteria) this;
		}

		public Criteria andCtlTypeIsNotNull() {
			addCriterion("ctl_type is not null");
			return (Criteria) this;
		}

		public Criteria andCtlTypeEqualTo(Integer value) {
			addCriterion("ctl_type =", value, "ctlType");
			return (Criteria) this;
		}

		public Criteria andCtlTypeNotEqualTo(Integer value) {
			addCriterion("ctl_type <>", value, "ctlType");
			return (Criteria) this;
		}

		public Criteria andCtlTypeGreaterThan(Integer value) {
			addCriterion("ctl_type >", value, "ctlType");
			return (Criteria) this;
		}

		public Criteria andCtlTypeGreaterThanOrEqualTo(Integer value) {
			addCriterion("ctl_type >=", value, "ctlType");
			return (Criteria) this;
		}

		public Criteria andCtlTypeLessThan(Integer value) {
			addCriterion("ctl_type <", value, "ctlType");
			return (Criteria) this;
		}

		public Criteria andCtlTypeLessThanOrEqualTo(Integer value) {
			addCriterion("ctl_type <=", value, "ctlType");
			return (Criteria) this;
		}

		public Criteria andCtlTypeIn(List<Integer> values) {
			addCriterion("ctl_type in", values, "ctlType");
			return (Criteria) this;
		}

		public Criteria andCtlTypeNotIn(List<Integer> values) {
			addCriterion("ctl_type not in", values, "ctlType");
			return (Criteria) this;
		}

		public Criteria andCtlTypeBetween(Integer value1, Integer value2) {
			addCriterion("ctl_type between", value1, value2, "ctlType");
			return (Criteria) this;
		}

		public Criteria andCtlTypeNotBetween(Integer value1, Integer value2) {
			addCriterion("ctl_type not between", value1, value2, "ctlType");
			return (Criteria) this;
		}

		public Criteria andOutTypeIsNull() {
			addCriterion("out_type is null");
			return (Criteria) this;
		}

		public Criteria andOutTypeIsNotNull() {
			addCriterion("out_type is not null");
			return (Criteria) this;
		}

		public Criteria andOutTypeEqualTo(Integer value) {
			addCriterion("out_type =", value, "outType");
			return (Criteria) this;
		}

		public Criteria andOutTypeNotEqualTo(Integer value) {
			addCriterion("out_type <>", value, "outType");
			return (Criteria) this;
		}

		public Criteria andOutTypeGreaterThan(Integer value) {
			addCriterion("out_type >", value, "outType");
			return (Criteria) this;
		}

		public Criteria andOutTypeGreaterThanOrEqualTo(Integer value) {
			addCriterion("out_type >=", value, "outType");
			return (Criteria) this;
		}

		public Criteria andOutTypeLessThan(Integer value) {
			addCriterion("out_type <", value, "outType");
			return (Criteria) this;
		}

		public Criteria andOutTypeLessThanOrEqualTo(Integer value) {
			addCriterion("out_type <=", value, "outType");
			return (Criteria) this;
		}

		public Criteria andOutTypeIn(List<Integer> values) {
			addCriterion("out_type in", values, "outType");
			return (Criteria) this;
		}

		public Criteria andOutTypeNotIn(List<Integer> values) {
			addCriterion("out_type not in", values, "outType");
			return (Criteria) this;
		}

		public Criteria andOutTypeBetween(Integer value1, Integer value2) {
			addCriterion("out_type between", value1, value2, "outType");
			return (Criteria) this;
		}

		public Criteria andOutTypeNotBetween(Integer value1, Integer value2) {
			addCriterion("out_type not between", value1, value2, "outType");
			return (Criteria) this;
		}

		public Criteria andOutValueIsNull() {
			addCriterion("out_value is null");
			return (Criteria) this;
		}

		public Criteria andOutValueIsNotNull() {
			addCriterion("out_value is not null");
			return (Criteria) this;
		}

		public Criteria andOutValueEqualTo(Integer value) {
			addCriterion("out_value =", value, "outValue");
			return (Criteria) this;
		}

		public Criteria andOutValueNotEqualTo(Integer value) {
			addCriterion("out_value <>", value, "outValue");
			return (Criteria) this;
		}

		public Criteria andOutValueGreaterThan(Integer value) {
			addCriterion("out_value >", value, "outValue");
			return (Criteria) this;
		}

		public Criteria andOutValueGreaterThanOrEqualTo(Integer value) {
			addCriterion("out_value >=", value, "outValue");
			return (Criteria) this;
		}

		public Criteria andOutValueLessThan(Integer value) {
			addCriterion("out_value <", value, "outValue");
			return (Criteria) this;
		}

		public Criteria andOutValueLessThanOrEqualTo(Integer value) {
			addCriterion("out_value <=", value, "outValue");
			return (Criteria) this;
		}

		public Criteria andOutValueIn(List<Integer> values) {
			addCriterion("out_value in", values, "outValue");
			return (Criteria) this;
		}

		public Criteria andOutValueNotIn(List<Integer> values) {
			addCriterion("out_value not in", values, "outValue");
			return (Criteria) this;
		}

		public Criteria andOutValueBetween(Integer value1, Integer value2) {
			addCriterion("out_value between", value1, value2, "outValue");
			return (Criteria) this;
		}

		public Criteria andOutValueNotBetween(Integer value1, Integer value2) {
			addCriterion("out_value not between", value1, value2, "outValue");
			return (Criteria) this;
		}

		public Criteria andVersionIsNull() {
			addCriterion("version is null");
			return (Criteria) this;
		}

		public Criteria andVersionIsNotNull() {
			addCriterion("version is not null");
			return (Criteria) this;
		}

		public Criteria andVersionEqualTo(Integer value) {
			addCriterion("version =", value, "version");
			return (Criteria) this;
		}

		public Criteria andVersionNotEqualTo(Integer value) {
			addCriterion("version <>", value, "version");
			return (Criteria) this;
		}

		public Criteria andVersionGreaterThan(Integer value) {
			addCriterion("version >", value, "version");
			return (Criteria) this;
		}

		public Criteria andVersionGreaterThanOrEqualTo(Integer value) {
			addCriterion("version >=", value, "version");
			return (Criteria) this;
		}

		public Criteria andVersionLessThan(Integer value) {
			addCriterion("version <", value, "version");
			return (Criteria) this;
		}

		public Criteria andVersionLessThanOrEqualTo(Integer value) {
			addCriterion("version <=", value, "version");
			return (Criteria) this;
		}

		public Criteria andVersionIn(List<Integer> values) {
			addCriterion("version in", values, "version");
			return (Criteria) this;
		}

		public Criteria andVersionNotIn(List<Integer> values) {
			addCriterion("version not in", values, "version");
			return (Criteria) this;
		}

		public Criteria andVersionBetween(Integer value1, Integer value2) {
			addCriterion("version between", value1, value2, "version");
			return (Criteria) this;
		}

		public Criteria andVersionNotBetween(Integer value1, Integer value2) {
			addCriterion("version not between", value1, value2, "version");
			return (Criteria) this;
		}

		public Criteria andRemarkIsNull() {
			addCriterion("remark is null");
			return (Criteria) this;
		}

		public Criteria andRemarkIsNotNull() {
			addCriterion("remark is not null");
			return (Criteria) this;
		}

		public Criteria andRemarkEqualTo(String value) {
			addCriterion("remark =", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkNotEqualTo(String value) {
			addCriterion("remark <>", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkGreaterThan(String value) {
			addCriterion("remark >", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkGreaterThanOrEqualTo(String value) {
			addCriterion("remark >=", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkLessThan(String value) {
			addCriterion("remark <", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkLessThanOrEqualTo(String value) {
			addCriterion("remark <=", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkLike(String value) {
			addCriterion("remark like", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkNotLike(String value) {
			addCriterion("remark not like", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkIn(List<String> values) {
			addCriterion("remark in", values, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkNotIn(List<String> values) {
			addCriterion("remark not in", values, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkBetween(String value1, String value2) {
			addCriterion("remark between", value1, value2, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkNotBetween(String value1, String value2) {
			addCriterion("remark not between", value1, value2, "remark");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table logic
	 * @mbggenerated  Sat Aug 25 14:14:03 CST 2012
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table logic
     *
     * @mbggenerated do_not_delete_during_merge Sun Jul 29 21:04:38 CST 2012
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}