package com.survey.panelsns.model.entity;

public class LogicUnit {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column logic_unit.id
	 * @mbggenerated  Sat Aug 25 14:14:03 CST 2012
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column logic_unit.ques_naire_id
	 * @mbggenerated  Sat Aug 25 14:14:03 CST 2012
	 */
	private Long quesNaireId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column logic_unit.ques_id
	 * @mbggenerated  Sat Aug 25 14:14:03 CST 2012
	 */
	private Long quesId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column logic_unit.ques_option_id
	 * @mbggenerated  Sat Aug 25 14:14:03 CST 2012
	 */
	private Long quesOptionId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column logic_unit.ques_option_val
	 * @mbggenerated  Sat Aug 25 14:14:03 CST 2012
	 */
	private String quesOptionVal;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column logic_unit.logic_condition_id
	 * @mbggenerated  Sat Aug 25 14:14:03 CST 2012
	 */
	private Long logicConditionId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column logic_unit.version
	 * @mbggenerated  Sat Aug 25 14:14:03 CST 2012
	 */
	private Integer version;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column logic_unit.remark
	 * @mbggenerated  Sat Aug 25 14:14:03 CST 2012
	 */
	private String remark;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column logic_unit.id
	 * @return  the value of logic_unit.id
	 * @mbggenerated  Sat Aug 25 14:14:03 CST 2012
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column logic_unit.id
	 * @param id  the value for logic_unit.id
	 * @mbggenerated  Sat Aug 25 14:14:03 CST 2012
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column logic_unit.ques_naire_id
	 * @return  the value of logic_unit.ques_naire_id
	 * @mbggenerated  Sat Aug 25 14:14:03 CST 2012
	 */
	public Long getQuesNaireId() {
		return quesNaireId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column logic_unit.ques_naire_id
	 * @param quesNaireId  the value for logic_unit.ques_naire_id
	 * @mbggenerated  Sat Aug 25 14:14:03 CST 2012
	 */
	public void setQuesNaireId(Long quesNaireId) {
		this.quesNaireId = quesNaireId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column logic_unit.ques_id
	 * @return  the value of logic_unit.ques_id
	 * @mbggenerated  Sat Aug 25 14:14:03 CST 2012
	 */
	public Long getQuesId() {
		return quesId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column logic_unit.ques_id
	 * @param quesId  the value for logic_unit.ques_id
	 * @mbggenerated  Sat Aug 25 14:14:03 CST 2012
	 */
	public void setQuesId(Long quesId) {
		this.quesId = quesId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column logic_unit.ques_option_id
	 * @return  the value of logic_unit.ques_option_id
	 * @mbggenerated  Sat Aug 25 14:14:03 CST 2012
	 */
	public Long getQuesOptionId() {
		return quesOptionId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column logic_unit.ques_option_id
	 * @param quesOptionId  the value for logic_unit.ques_option_id
	 * @mbggenerated  Sat Aug 25 14:14:03 CST 2012
	 */
	public void setQuesOptionId(Long quesOptionId) {
		this.quesOptionId = quesOptionId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column logic_unit.ques_option_val
	 * @return  the value of logic_unit.ques_option_val
	 * @mbggenerated  Sat Aug 25 14:14:03 CST 2012
	 */
	public String getQuesOptionVal() {
		return quesOptionVal;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column logic_unit.ques_option_val
	 * @param quesOptionVal  the value for logic_unit.ques_option_val
	 * @mbggenerated  Sat Aug 25 14:14:03 CST 2012
	 */
	public void setQuesOptionVal(String quesOptionVal) {
		this.quesOptionVal = quesOptionVal;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column logic_unit.logic_condition_id
	 * @return  the value of logic_unit.logic_condition_id
	 * @mbggenerated  Sat Aug 25 14:14:03 CST 2012
	 */
	public Long getLogicConditionId() {
		return logicConditionId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column logic_unit.logic_condition_id
	 * @param logicConditionId  the value for logic_unit.logic_condition_id
	 * @mbggenerated  Sat Aug 25 14:14:03 CST 2012
	 */
	public void setLogicConditionId(Long logicConditionId) {
		this.logicConditionId = logicConditionId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column logic_unit.version
	 * @return  the value of logic_unit.version
	 * @mbggenerated  Sat Aug 25 14:14:03 CST 2012
	 */
	public Integer getVersion() {
		return version;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column logic_unit.version
	 * @param version  the value for logic_unit.version
	 * @mbggenerated  Sat Aug 25 14:14:03 CST 2012
	 */
	public void setVersion(Integer version) {
		this.version = version;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column logic_unit.remark
	 * @return  the value of logic_unit.remark
	 * @mbggenerated  Sat Aug 25 14:14:03 CST 2012
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column logic_unit.remark
	 * @param remark  the value for logic_unit.remark
	 * @mbggenerated  Sat Aug 25 14:14:03 CST 2012
	 */
	public void setRemark(String remark) {
		this.remark = remark;
	}
}