package com.survey.panelsns.model.entity;

public class LogicCondition {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column logic_condition.id
	 * @mbggenerated  Sun Jul 29 21:06:13 CST 2012
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column logic_condition.logic_group_id
	 * @mbggenerated  Sun Jul 29 21:06:13 CST 2012
	 */
	private Long logicGroupId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column logic_condition.expression_val
	 * @mbggenerated  Sun Jul 29 21:06:13 CST 2012
	 */
	private Long expressionVal;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column logic_condition.login_id
	 * @mbggenerated  Sun Jul 29 21:06:13 CST 2012
	 */
	private Long loginId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column logic_condition.version
	 * @mbggenerated  Sun Jul 29 21:06:13 CST 2012
	 */
	private Integer version;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column logic_condition.remark
	 * @mbggenerated  Sun Jul 29 21:06:13 CST 2012
	 */
	private String remark;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column logic_condition.expression
	 * @mbggenerated  Sun Jul 29 21:06:13 CST 2012
	 */
	private String expression;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column logic_condition.id
	 * @return  the value of logic_condition.id
	 * @mbggenerated  Sun Jul 29 21:06:13 CST 2012
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column logic_condition.id
	 * @param id  the value for logic_condition.id
	 * @mbggenerated  Sun Jul 29 21:06:13 CST 2012
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column logic_condition.logic_group_id
	 * @return  the value of logic_condition.logic_group_id
	 * @mbggenerated  Sun Jul 29 21:06:13 CST 2012
	 */
	public Long getLogicGroupId() {
		return logicGroupId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column logic_condition.logic_group_id
	 * @param logicGroupId  the value for logic_condition.logic_group_id
	 * @mbggenerated  Sun Jul 29 21:06:13 CST 2012
	 */
	public void setLogicGroupId(Long logicGroupId) {
		this.logicGroupId = logicGroupId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column logic_condition.expression_val
	 * @return  the value of logic_condition.expression_val
	 * @mbggenerated  Sun Jul 29 21:06:13 CST 2012
	 */
	public Long getExpressionVal() {
		return expressionVal;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column logic_condition.expression_val
	 * @param expressionVal  the value for logic_condition.expression_val
	 * @mbggenerated  Sun Jul 29 21:06:13 CST 2012
	 */
	public void setExpressionVal(Long expressionVal) {
		this.expressionVal = expressionVal;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column logic_condition.login_id
	 * @return  the value of logic_condition.login_id
	 * @mbggenerated  Sun Jul 29 21:06:13 CST 2012
	 */
	public Long getLoginId() {
		return loginId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column logic_condition.login_id
	 * @param loginId  the value for logic_condition.login_id
	 * @mbggenerated  Sun Jul 29 21:06:13 CST 2012
	 */
	public void setLoginId(Long loginId) {
		this.loginId = loginId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column logic_condition.version
	 * @return  the value of logic_condition.version
	 * @mbggenerated  Sun Jul 29 21:06:13 CST 2012
	 */
	public Integer getVersion() {
		return version;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column logic_condition.version
	 * @param version  the value for logic_condition.version
	 * @mbggenerated  Sun Jul 29 21:06:13 CST 2012
	 */
	public void setVersion(Integer version) {
		this.version = version;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column logic_condition.remark
	 * @return  the value of logic_condition.remark
	 * @mbggenerated  Sun Jul 29 21:06:13 CST 2012
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column logic_condition.remark
	 * @param remark  the value for logic_condition.remark
	 * @mbggenerated  Sun Jul 29 21:06:13 CST 2012
	 */
	public void setRemark(String remark) {
		this.remark = remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column logic_condition.expression
	 * @return  the value of logic_condition.expression
	 * @mbggenerated  Sun Jul 29 21:06:13 CST 2012
	 */
	public String getExpression() {
		return expression;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column logic_condition.expression
	 * @param expression  the value for logic_condition.expression
	 * @mbggenerated  Sun Jul 29 21:06:13 CST 2012
	 */
	public void setExpression(String expression) {
		this.expression = expression;
	}
}