package com.survey.panelsns.model.entity;

public class Project {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project.id
	 * @mbggenerated  Tue Sep 18 00:39:07 CST 2012
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project.user_id
	 * @mbggenerated  Tue Sep 18 00:39:07 CST 2012
	 */
	private Long userId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project.id
	 * @return  the value of project.id
	 * @mbggenerated  Tue Sep 18 00:39:07 CST 2012
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project.id
	 * @param id  the value for project.id
	 * @mbggenerated  Tue Sep 18 00:39:07 CST 2012
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project.user_id
	 * @return  the value of project.user_id
	 * @mbggenerated  Tue Sep 18 00:39:07 CST 2012
	 */
	public Long getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project.user_id
	 * @param userId  the value for project.user_id
	 * @mbggenerated  Tue Sep 18 00:39:07 CST 2012
	 */
	public void setUserId(Long userId) {
		this.userId = userId;
	}
}