package com.survey.panelsns.model.entity;

public class QuesOption {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ques_option.id
	 * @mbggenerated  Sat Aug 25 14:14:03 CST 2012
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ques_option.ques_id
	 * @mbggenerated  Sat Aug 25 14:14:03 CST 2012
	 */
	private Long quesId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ques_option.serial_no
	 * @mbggenerated  Sat Aug 25 14:14:03 CST 2012
	 */
	private Integer serialNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ques_option.title
	 * @mbggenerated  Sat Aug 25 14:14:03 CST 2012
	 */
	private String title;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ques_option.content
	 * @mbggenerated  Sat Aug 25 14:14:03 CST 2012
	 */
	private String content;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ques_option.version
	 * @mbggenerated  Sat Aug 25 14:14:03 CST 2012
	 */
	private Integer version;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ques_option.remark
	 * @mbggenerated  Sat Aug 25 14:14:03 CST 2012
	 */
	private String remark;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ques_option.id
	 * @return  the value of ques_option.id
	 * @mbggenerated  Sat Aug 25 14:14:03 CST 2012
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ques_option.id
	 * @param id  the value for ques_option.id
	 * @mbggenerated  Sat Aug 25 14:14:03 CST 2012
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ques_option.ques_id
	 * @return  the value of ques_option.ques_id
	 * @mbggenerated  Sat Aug 25 14:14:03 CST 2012
	 */
	public Long getQuesId() {
		return quesId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ques_option.ques_id
	 * @param quesId  the value for ques_option.ques_id
	 * @mbggenerated  Sat Aug 25 14:14:03 CST 2012
	 */
	public void setQuesId(Long quesId) {
		this.quesId = quesId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ques_option.serial_no
	 * @return  the value of ques_option.serial_no
	 * @mbggenerated  Sat Aug 25 14:14:03 CST 2012
	 */
	public Integer getSerialNo() {
		return serialNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ques_option.serial_no
	 * @param serialNo  the value for ques_option.serial_no
	 * @mbggenerated  Sat Aug 25 14:14:03 CST 2012
	 */
	public void setSerialNo(Integer serialNo) {
		this.serialNo = serialNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ques_option.title
	 * @return  the value of ques_option.title
	 * @mbggenerated  Sat Aug 25 14:14:03 CST 2012
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ques_option.title
	 * @param title  the value for ques_option.title
	 * @mbggenerated  Sat Aug 25 14:14:03 CST 2012
	 */
	public void setTitle(String title) {
		this.title = title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ques_option.content
	 * @return  the value of ques_option.content
	 * @mbggenerated  Sat Aug 25 14:14:03 CST 2012
	 */
	public String getContent() {
		return content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ques_option.content
	 * @param content  the value for ques_option.content
	 * @mbggenerated  Sat Aug 25 14:14:03 CST 2012
	 */
	public void setContent(String content) {
		this.content = content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ques_option.version
	 * @return  the value of ques_option.version
	 * @mbggenerated  Sat Aug 25 14:14:03 CST 2012
	 */
	public Integer getVersion() {
		return version;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ques_option.version
	 * @param version  the value for ques_option.version
	 * @mbggenerated  Sat Aug 25 14:14:03 CST 2012
	 */
	public void setVersion(Integer version) {
		this.version = version;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ques_option.remark
	 * @return  the value of ques_option.remark
	 * @mbggenerated  Sat Aug 25 14:14:03 CST 2012
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ques_option.remark
	 * @param remark  the value for ques_option.remark
	 * @mbggenerated  Sat Aug 25 14:14:03 CST 2012
	 */
	public void setRemark(String remark) {
		this.remark = remark;
	}
}