package com.survey.panelsns.model.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class QuesNaireExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table ques_naire
	 * @mbggenerated  Tue Sep 18 00:39:07 CST 2012
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table ques_naire
	 * @mbggenerated  Tue Sep 18 00:39:07 CST 2012
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table ques_naire
	 * @mbggenerated  Tue Sep 18 00:39:07 CST 2012
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ques_naire
	 * @mbggenerated  Tue Sep 18 00:39:07 CST 2012
	 */
	public QuesNaireExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ques_naire
	 * @mbggenerated  Tue Sep 18 00:39:07 CST 2012
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ques_naire
	 * @mbggenerated  Tue Sep 18 00:39:07 CST 2012
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ques_naire
	 * @mbggenerated  Tue Sep 18 00:39:07 CST 2012
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ques_naire
	 * @mbggenerated  Tue Sep 18 00:39:07 CST 2012
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ques_naire
	 * @mbggenerated  Tue Sep 18 00:39:07 CST 2012
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ques_naire
	 * @mbggenerated  Tue Sep 18 00:39:07 CST 2012
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ques_naire
	 * @mbggenerated  Tue Sep 18 00:39:07 CST 2012
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ques_naire
	 * @mbggenerated  Tue Sep 18 00:39:07 CST 2012
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ques_naire
	 * @mbggenerated  Tue Sep 18 00:39:07 CST 2012
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ques_naire
	 * @mbggenerated  Tue Sep 18 00:39:07 CST 2012
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table ques_naire
	 * @mbggenerated  Tue Sep 18 00:39:07 CST 2012
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		protected void addCriterionForJDBCDate(String condition, Date value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value.getTime()), property);
		}

		protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property + " cannot be null or empty");
			}
			List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
			Iterator<Date> iter = values.iterator();
			while (iter.hasNext()) {
				dateList.add(new java.sql.Date(iter.next().getTime()));
			}
			addCriterion(condition, dateList, property);
		}

		protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Long value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Long value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Long value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Long value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Long value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Long value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Long> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Long> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Long value1, Long value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Long value1, Long value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andSurveyIdIsNull() {
			addCriterion("survey_id is null");
			return (Criteria) this;
		}

		public Criteria andSurveyIdIsNotNull() {
			addCriterion("survey_id is not null");
			return (Criteria) this;
		}

		public Criteria andSurveyIdEqualTo(Long value) {
			addCriterion("survey_id =", value, "surveyId");
			return (Criteria) this;
		}

		public Criteria andSurveyIdNotEqualTo(Long value) {
			addCriterion("survey_id <>", value, "surveyId");
			return (Criteria) this;
		}

		public Criteria andSurveyIdGreaterThan(Long value) {
			addCriterion("survey_id >", value, "surveyId");
			return (Criteria) this;
		}

		public Criteria andSurveyIdGreaterThanOrEqualTo(Long value) {
			addCriterion("survey_id >=", value, "surveyId");
			return (Criteria) this;
		}

		public Criteria andSurveyIdLessThan(Long value) {
			addCriterion("survey_id <", value, "surveyId");
			return (Criteria) this;
		}

		public Criteria andSurveyIdLessThanOrEqualTo(Long value) {
			addCriterion("survey_id <=", value, "surveyId");
			return (Criteria) this;
		}

		public Criteria andSurveyIdIn(List<Long> values) {
			addCriterion("survey_id in", values, "surveyId");
			return (Criteria) this;
		}

		public Criteria andSurveyIdNotIn(List<Long> values) {
			addCriterion("survey_id not in", values, "surveyId");
			return (Criteria) this;
		}

		public Criteria andSurveyIdBetween(Long value1, Long value2) {
			addCriterion("survey_id between", value1, value2, "surveyId");
			return (Criteria) this;
		}

		public Criteria andSurveyIdNotBetween(Long value1, Long value2) {
			addCriterion("survey_id not between", value1, value2, "surveyId");
			return (Criteria) this;
		}

		public Criteria andTemplateIdIsNull() {
			addCriterion("template_id is null");
			return (Criteria) this;
		}

		public Criteria andTemplateIdIsNotNull() {
			addCriterion("template_id is not null");
			return (Criteria) this;
		}

		public Criteria andTemplateIdEqualTo(Long value) {
			addCriterion("template_id =", value, "templateId");
			return (Criteria) this;
		}

		public Criteria andTemplateIdNotEqualTo(Long value) {
			addCriterion("template_id <>", value, "templateId");
			return (Criteria) this;
		}

		public Criteria andTemplateIdGreaterThan(Long value) {
			addCriterion("template_id >", value, "templateId");
			return (Criteria) this;
		}

		public Criteria andTemplateIdGreaterThanOrEqualTo(Long value) {
			addCriterion("template_id >=", value, "templateId");
			return (Criteria) this;
		}

		public Criteria andTemplateIdLessThan(Long value) {
			addCriterion("template_id <", value, "templateId");
			return (Criteria) this;
		}

		public Criteria andTemplateIdLessThanOrEqualTo(Long value) {
			addCriterion("template_id <=", value, "templateId");
			return (Criteria) this;
		}

		public Criteria andTemplateIdIn(List<Long> values) {
			addCriterion("template_id in", values, "templateId");
			return (Criteria) this;
		}

		public Criteria andTemplateIdNotIn(List<Long> values) {
			addCriterion("template_id not in", values, "templateId");
			return (Criteria) this;
		}

		public Criteria andTemplateIdBetween(Long value1, Long value2) {
			addCriterion("template_id between", value1, value2, "templateId");
			return (Criteria) this;
		}

		public Criteria andTemplateIdNotBetween(Long value1, Long value2) {
			addCriterion("template_id not between", value1, value2, "templateId");
			return (Criteria) this;
		}

		public Criteria andTypeIsNull() {
			addCriterion("type is null");
			return (Criteria) this;
		}

		public Criteria andTypeIsNotNull() {
			addCriterion("type is not null");
			return (Criteria) this;
		}

		public Criteria andTypeEqualTo(Integer value) {
			addCriterion("type =", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeNotEqualTo(Integer value) {
			addCriterion("type <>", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeGreaterThan(Integer value) {
			addCriterion("type >", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeGreaterThanOrEqualTo(Integer value) {
			addCriterion("type >=", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeLessThan(Integer value) {
			addCriterion("type <", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeLessThanOrEqualTo(Integer value) {
			addCriterion("type <=", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeIn(List<Integer> values) {
			addCriterion("type in", values, "type");
			return (Criteria) this;
		}

		public Criteria andTypeNotIn(List<Integer> values) {
			addCriterion("type not in", values, "type");
			return (Criteria) this;
		}

		public Criteria andTypeBetween(Integer value1, Integer value2) {
			addCriterion("type between", value1, value2, "type");
			return (Criteria) this;
		}

		public Criteria andTypeNotBetween(Integer value1, Integer value2) {
			addCriterion("type not between", value1, value2, "type");
			return (Criteria) this;
		}

		public Criteria andNameIsNull() {
			addCriterion("name is null");
			return (Criteria) this;
		}

		public Criteria andNameIsNotNull() {
			addCriterion("name is not null");
			return (Criteria) this;
		}

		public Criteria andNameEqualTo(String value) {
			addCriterion("name =", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotEqualTo(String value) {
			addCriterion("name <>", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThan(String value) {
			addCriterion("name >", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThanOrEqualTo(String value) {
			addCriterion("name >=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThan(String value) {
			addCriterion("name <", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThanOrEqualTo(String value) {
			addCriterion("name <=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLike(String value) {
			addCriterion("name like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotLike(String value) {
			addCriterion("name not like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameIn(List<String> values) {
			addCriterion("name in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotIn(List<String> values) {
			addCriterion("name not in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameBetween(String value1, String value2) {
			addCriterion("name between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotBetween(String value1, String value2) {
			addCriterion("name not between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andCodeIsNull() {
			addCriterion("code is null");
			return (Criteria) this;
		}

		public Criteria andCodeIsNotNull() {
			addCriterion("code is not null");
			return (Criteria) this;
		}

		public Criteria andCodeEqualTo(String value) {
			addCriterion("code =", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeNotEqualTo(String value) {
			addCriterion("code <>", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeGreaterThan(String value) {
			addCriterion("code >", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeGreaterThanOrEqualTo(String value) {
			addCriterion("code >=", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeLessThan(String value) {
			addCriterion("code <", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeLessThanOrEqualTo(String value) {
			addCriterion("code <=", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeLike(String value) {
			addCriterion("code like", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeNotLike(String value) {
			addCriterion("code not like", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeIn(List<String> values) {
			addCriterion("code in", values, "code");
			return (Criteria) this;
		}

		public Criteria andCodeNotIn(List<String> values) {
			addCriterion("code not in", values, "code");
			return (Criteria) this;
		}

		public Criteria andCodeBetween(String value1, String value2) {
			addCriterion("code between", value1, value2, "code");
			return (Criteria) this;
		}

		public Criteria andCodeNotBetween(String value1, String value2) {
			addCriterion("code not between", value1, value2, "code");
			return (Criteria) this;
		}

		public Criteria andHeaderIsNull() {
			addCriterion("header is null");
			return (Criteria) this;
		}

		public Criteria andHeaderIsNotNull() {
			addCriterion("header is not null");
			return (Criteria) this;
		}

		public Criteria andHeaderEqualTo(String value) {
			addCriterion("header =", value, "header");
			return (Criteria) this;
		}

		public Criteria andHeaderNotEqualTo(String value) {
			addCriterion("header <>", value, "header");
			return (Criteria) this;
		}

		public Criteria andHeaderGreaterThan(String value) {
			addCriterion("header >", value, "header");
			return (Criteria) this;
		}

		public Criteria andHeaderGreaterThanOrEqualTo(String value) {
			addCriterion("header >=", value, "header");
			return (Criteria) this;
		}

		public Criteria andHeaderLessThan(String value) {
			addCriterion("header <", value, "header");
			return (Criteria) this;
		}

		public Criteria andHeaderLessThanOrEqualTo(String value) {
			addCriterion("header <=", value, "header");
			return (Criteria) this;
		}

		public Criteria andHeaderLike(String value) {
			addCriterion("header like", value, "header");
			return (Criteria) this;
		}

		public Criteria andHeaderNotLike(String value) {
			addCriterion("header not like", value, "header");
			return (Criteria) this;
		}

		public Criteria andHeaderIn(List<String> values) {
			addCriterion("header in", values, "header");
			return (Criteria) this;
		}

		public Criteria andHeaderNotIn(List<String> values) {
			addCriterion("header not in", values, "header");
			return (Criteria) this;
		}

		public Criteria andHeaderBetween(String value1, String value2) {
			addCriterion("header between", value1, value2, "header");
			return (Criteria) this;
		}

		public Criteria andHeaderNotBetween(String value1, String value2) {
			addCriterion("header not between", value1, value2, "header");
			return (Criteria) this;
		}

		public Criteria andTitleIsNull() {
			addCriterion("title is null");
			return (Criteria) this;
		}

		public Criteria andTitleIsNotNull() {
			addCriterion("title is not null");
			return (Criteria) this;
		}

		public Criteria andTitleEqualTo(String value) {
			addCriterion("title =", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleNotEqualTo(String value) {
			addCriterion("title <>", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleGreaterThan(String value) {
			addCriterion("title >", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleGreaterThanOrEqualTo(String value) {
			addCriterion("title >=", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleLessThan(String value) {
			addCriterion("title <", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleLessThanOrEqualTo(String value) {
			addCriterion("title <=", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleLike(String value) {
			addCriterion("title like", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleNotLike(String value) {
			addCriterion("title not like", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleIn(List<String> values) {
			addCriterion("title in", values, "title");
			return (Criteria) this;
		}

		public Criteria andTitleNotIn(List<String> values) {
			addCriterion("title not in", values, "title");
			return (Criteria) this;
		}

		public Criteria andTitleBetween(String value1, String value2) {
			addCriterion("title between", value1, value2, "title");
			return (Criteria) this;
		}

		public Criteria andTitleNotBetween(String value1, String value2) {
			addCriterion("title not between", value1, value2, "title");
			return (Criteria) this;
		}

		public Criteria andFooterIsNull() {
			addCriterion("footer is null");
			return (Criteria) this;
		}

		public Criteria andFooterIsNotNull() {
			addCriterion("footer is not null");
			return (Criteria) this;
		}

		public Criteria andFooterEqualTo(String value) {
			addCriterion("footer =", value, "footer");
			return (Criteria) this;
		}

		public Criteria andFooterNotEqualTo(String value) {
			addCriterion("footer <>", value, "footer");
			return (Criteria) this;
		}

		public Criteria andFooterGreaterThan(String value) {
			addCriterion("footer >", value, "footer");
			return (Criteria) this;
		}

		public Criteria andFooterGreaterThanOrEqualTo(String value) {
			addCriterion("footer >=", value, "footer");
			return (Criteria) this;
		}

		public Criteria andFooterLessThan(String value) {
			addCriterion("footer <", value, "footer");
			return (Criteria) this;
		}

		public Criteria andFooterLessThanOrEqualTo(String value) {
			addCriterion("footer <=", value, "footer");
			return (Criteria) this;
		}

		public Criteria andFooterLike(String value) {
			addCriterion("footer like", value, "footer");
			return (Criteria) this;
		}

		public Criteria andFooterNotLike(String value) {
			addCriterion("footer not like", value, "footer");
			return (Criteria) this;
		}

		public Criteria andFooterIn(List<String> values) {
			addCriterion("footer in", values, "footer");
			return (Criteria) this;
		}

		public Criteria andFooterNotIn(List<String> values) {
			addCriterion("footer not in", values, "footer");
			return (Criteria) this;
		}

		public Criteria andFooterBetween(String value1, String value2) {
			addCriterion("footer between", value1, value2, "footer");
			return (Criteria) this;
		}

		public Criteria andFooterNotBetween(String value1, String value2) {
			addCriterion("footer not between", value1, value2, "footer");
			return (Criteria) this;
		}

		public Criteria andPriorityIsNull() {
			addCriterion("priority is null");
			return (Criteria) this;
		}

		public Criteria andPriorityIsNotNull() {
			addCriterion("priority is not null");
			return (Criteria) this;
		}

		public Criteria andPriorityEqualTo(Integer value) {
			addCriterion("priority =", value, "priority");
			return (Criteria) this;
		}

		public Criteria andPriorityNotEqualTo(Integer value) {
			addCriterion("priority <>", value, "priority");
			return (Criteria) this;
		}

		public Criteria andPriorityGreaterThan(Integer value) {
			addCriterion("priority >", value, "priority");
			return (Criteria) this;
		}

		public Criteria andPriorityGreaterThanOrEqualTo(Integer value) {
			addCriterion("priority >=", value, "priority");
			return (Criteria) this;
		}

		public Criteria andPriorityLessThan(Integer value) {
			addCriterion("priority <", value, "priority");
			return (Criteria) this;
		}

		public Criteria andPriorityLessThanOrEqualTo(Integer value) {
			addCriterion("priority <=", value, "priority");
			return (Criteria) this;
		}

		public Criteria andPriorityIn(List<Integer> values) {
			addCriterion("priority in", values, "priority");
			return (Criteria) this;
		}

		public Criteria andPriorityNotIn(List<Integer> values) {
			addCriterion("priority not in", values, "priority");
			return (Criteria) this;
		}

		public Criteria andPriorityBetween(Integer value1, Integer value2) {
			addCriterion("priority between", value1, value2, "priority");
			return (Criteria) this;
		}

		public Criteria andPriorityNotBetween(Integer value1, Integer value2) {
			addCriterion("priority not between", value1, value2, "priority");
			return (Criteria) this;
		}

		public Criteria andDescriptIsNull() {
			addCriterion("descript is null");
			return (Criteria) this;
		}

		public Criteria andDescriptIsNotNull() {
			addCriterion("descript is not null");
			return (Criteria) this;
		}

		public Criteria andDescriptEqualTo(String value) {
			addCriterion("descript =", value, "descript");
			return (Criteria) this;
		}

		public Criteria andDescriptNotEqualTo(String value) {
			addCriterion("descript <>", value, "descript");
			return (Criteria) this;
		}

		public Criteria andDescriptGreaterThan(String value) {
			addCriterion("descript >", value, "descript");
			return (Criteria) this;
		}

		public Criteria andDescriptGreaterThanOrEqualTo(String value) {
			addCriterion("descript >=", value, "descript");
			return (Criteria) this;
		}

		public Criteria andDescriptLessThan(String value) {
			addCriterion("descript <", value, "descript");
			return (Criteria) this;
		}

		public Criteria andDescriptLessThanOrEqualTo(String value) {
			addCriterion("descript <=", value, "descript");
			return (Criteria) this;
		}

		public Criteria andDescriptLike(String value) {
			addCriterion("descript like", value, "descript");
			return (Criteria) this;
		}

		public Criteria andDescriptNotLike(String value) {
			addCriterion("descript not like", value, "descript");
			return (Criteria) this;
		}

		public Criteria andDescriptIn(List<String> values) {
			addCriterion("descript in", values, "descript");
			return (Criteria) this;
		}

		public Criteria andDescriptNotIn(List<String> values) {
			addCriterion("descript not in", values, "descript");
			return (Criteria) this;
		}

		public Criteria andDescriptBetween(String value1, String value2) {
			addCriterion("descript between", value1, value2, "descript");
			return (Criteria) this;
		}

		public Criteria andDescriptNotBetween(String value1, String value2) {
			addCriterion("descript not between", value1, value2, "descript");
			return (Criteria) this;
		}

		public Criteria andStatusIsNull() {
			addCriterion("status is null");
			return (Criteria) this;
		}

		public Criteria andStatusIsNotNull() {
			addCriterion("status is not null");
			return (Criteria) this;
		}

		public Criteria andStatusEqualTo(Integer value) {
			addCriterion("status =", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotEqualTo(Integer value) {
			addCriterion("status <>", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThan(Integer value) {
			addCriterion("status >", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
			addCriterion("status >=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThan(Integer value) {
			addCriterion("status <", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThanOrEqualTo(Integer value) {
			addCriterion("status <=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusIn(List<Integer> values) {
			addCriterion("status in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotIn(List<Integer> values) {
			addCriterion("status not in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusBetween(Integer value1, Integer value2) {
			addCriterion("status between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotBetween(Integer value1, Integer value2) {
			addCriterion("status not between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andTotalPageIsNull() {
			addCriterion("total_page is null");
			return (Criteria) this;
		}

		public Criteria andTotalPageIsNotNull() {
			addCriterion("total_page is not null");
			return (Criteria) this;
		}

		public Criteria andTotalPageEqualTo(Integer value) {
			addCriterion("total_page =", value, "totalPage");
			return (Criteria) this;
		}

		public Criteria andTotalPageNotEqualTo(Integer value) {
			addCriterion("total_page <>", value, "totalPage");
			return (Criteria) this;
		}

		public Criteria andTotalPageGreaterThan(Integer value) {
			addCriterion("total_page >", value, "totalPage");
			return (Criteria) this;
		}

		public Criteria andTotalPageGreaterThanOrEqualTo(Integer value) {
			addCriterion("total_page >=", value, "totalPage");
			return (Criteria) this;
		}

		public Criteria andTotalPageLessThan(Integer value) {
			addCriterion("total_page <", value, "totalPage");
			return (Criteria) this;
		}

		public Criteria andTotalPageLessThanOrEqualTo(Integer value) {
			addCriterion("total_page <=", value, "totalPage");
			return (Criteria) this;
		}

		public Criteria andTotalPageIn(List<Integer> values) {
			addCriterion("total_page in", values, "totalPage");
			return (Criteria) this;
		}

		public Criteria andTotalPageNotIn(List<Integer> values) {
			addCriterion("total_page not in", values, "totalPage");
			return (Criteria) this;
		}

		public Criteria andTotalPageBetween(Integer value1, Integer value2) {
			addCriterion("total_page between", value1, value2, "totalPage");
			return (Criteria) this;
		}

		public Criteria andTotalPageNotBetween(Integer value1, Integer value2) {
			addCriterion("total_page not between", value1, value2, "totalPage");
			return (Criteria) this;
		}

		public Criteria andCreateDateIsNull() {
			addCriterion("create_date is null");
			return (Criteria) this;
		}

		public Criteria andCreateDateIsNotNull() {
			addCriterion("create_date is not null");
			return (Criteria) this;
		}

		public Criteria andCreateDateEqualTo(Date value) {
			addCriterionForJDBCDate("create_date =", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateNotEqualTo(Date value) {
			addCriterionForJDBCDate("create_date <>", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateGreaterThan(Date value) {
			addCriterionForJDBCDate("create_date >", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("create_date >=", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateLessThan(Date value) {
			addCriterionForJDBCDate("create_date <", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("create_date <=", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateIn(List<Date> values) {
			addCriterionForJDBCDate("create_date in", values, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateNotIn(List<Date> values) {
			addCriterionForJDBCDate("create_date not in", values, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("create_date between", value1, value2, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("create_date not between", value1, value2, "createDate");
			return (Criteria) this;
		}

		public Criteria andUpdaetDateIsNull() {
			addCriterion("updaet_date is null");
			return (Criteria) this;
		}

		public Criteria andUpdaetDateIsNotNull() {
			addCriterion("updaet_date is not null");
			return (Criteria) this;
		}

		public Criteria andUpdaetDateEqualTo(Date value) {
			addCriterionForJDBCDate("updaet_date =", value, "updaetDate");
			return (Criteria) this;
		}

		public Criteria andUpdaetDateNotEqualTo(Date value) {
			addCriterionForJDBCDate("updaet_date <>", value, "updaetDate");
			return (Criteria) this;
		}

		public Criteria andUpdaetDateGreaterThan(Date value) {
			addCriterionForJDBCDate("updaet_date >", value, "updaetDate");
			return (Criteria) this;
		}

		public Criteria andUpdaetDateGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("updaet_date >=", value, "updaetDate");
			return (Criteria) this;
		}

		public Criteria andUpdaetDateLessThan(Date value) {
			addCriterionForJDBCDate("updaet_date <", value, "updaetDate");
			return (Criteria) this;
		}

		public Criteria andUpdaetDateLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("updaet_date <=", value, "updaetDate");
			return (Criteria) this;
		}

		public Criteria andUpdaetDateIn(List<Date> values) {
			addCriterionForJDBCDate("updaet_date in", values, "updaetDate");
			return (Criteria) this;
		}

		public Criteria andUpdaetDateNotIn(List<Date> values) {
			addCriterionForJDBCDate("updaet_date not in", values, "updaetDate");
			return (Criteria) this;
		}

		public Criteria andUpdaetDateBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("updaet_date between", value1, value2, "updaetDate");
			return (Criteria) this;
		}

		public Criteria andUpdaetDateNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("updaet_date not between", value1, value2, "updaetDate");
			return (Criteria) this;
		}

		public Criteria andVersionIsNull() {
			addCriterion("version is null");
			return (Criteria) this;
		}

		public Criteria andVersionIsNotNull() {
			addCriterion("version is not null");
			return (Criteria) this;
		}

		public Criteria andVersionEqualTo(Integer value) {
			addCriterion("version =", value, "version");
			return (Criteria) this;
		}

		public Criteria andVersionNotEqualTo(Integer value) {
			addCriterion("version <>", value, "version");
			return (Criteria) this;
		}

		public Criteria andVersionGreaterThan(Integer value) {
			addCriterion("version >", value, "version");
			return (Criteria) this;
		}

		public Criteria andVersionGreaterThanOrEqualTo(Integer value) {
			addCriterion("version >=", value, "version");
			return (Criteria) this;
		}

		public Criteria andVersionLessThan(Integer value) {
			addCriterion("version <", value, "version");
			return (Criteria) this;
		}

		public Criteria andVersionLessThanOrEqualTo(Integer value) {
			addCriterion("version <=", value, "version");
			return (Criteria) this;
		}

		public Criteria andVersionIn(List<Integer> values) {
			addCriterion("version in", values, "version");
			return (Criteria) this;
		}

		public Criteria andVersionNotIn(List<Integer> values) {
			addCriterion("version not in", values, "version");
			return (Criteria) this;
		}

		public Criteria andVersionBetween(Integer value1, Integer value2) {
			addCriterion("version between", value1, value2, "version");
			return (Criteria) this;
		}

		public Criteria andVersionNotBetween(Integer value1, Integer value2) {
			addCriterion("version not between", value1, value2, "version");
			return (Criteria) this;
		}

		public Criteria andRemarkIsNull() {
			addCriterion("remark is null");
			return (Criteria) this;
		}

		public Criteria andRemarkIsNotNull() {
			addCriterion("remark is not null");
			return (Criteria) this;
		}

		public Criteria andRemarkEqualTo(String value) {
			addCriterion("remark =", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkNotEqualTo(String value) {
			addCriterion("remark <>", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkGreaterThan(String value) {
			addCriterion("remark >", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkGreaterThanOrEqualTo(String value) {
			addCriterion("remark >=", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkLessThan(String value) {
			addCriterion("remark <", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkLessThanOrEqualTo(String value) {
			addCriterion("remark <=", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkLike(String value) {
			addCriterion("remark like", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkNotLike(String value) {
			addCriterion("remark not like", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkIn(List<String> values) {
			addCriterion("remark in", values, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkNotIn(List<String> values) {
			addCriterion("remark not in", values, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkBetween(String value1, String value2) {
			addCriterion("remark between", value1, value2, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkNotBetween(String value1, String value2) {
			addCriterion("remark not between", value1, value2, "remark");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table ques_naire
	 * @mbggenerated  Tue Sep 18 00:39:07 CST 2012
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ques_naire
     *
     * @mbggenerated do_not_delete_during_merge Sun Jul 29 21:04:38 CST 2012
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}