package com.survey.panelsns.model.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class QuesExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table ques
	 * @mbggenerated  Mon Sep 10 23:12:26 CST 2012
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table ques
	 * @mbggenerated  Mon Sep 10 23:12:26 CST 2012
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table ques
	 * @mbggenerated  Mon Sep 10 23:12:26 CST 2012
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ques
	 * @mbggenerated  Mon Sep 10 23:12:26 CST 2012
	 */
	public QuesExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ques
	 * @mbggenerated  Mon Sep 10 23:12:26 CST 2012
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ques
	 * @mbggenerated  Mon Sep 10 23:12:26 CST 2012
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ques
	 * @mbggenerated  Mon Sep 10 23:12:26 CST 2012
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ques
	 * @mbggenerated  Mon Sep 10 23:12:26 CST 2012
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ques
	 * @mbggenerated  Mon Sep 10 23:12:26 CST 2012
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ques
	 * @mbggenerated  Mon Sep 10 23:12:26 CST 2012
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ques
	 * @mbggenerated  Mon Sep 10 23:12:26 CST 2012
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ques
	 * @mbggenerated  Mon Sep 10 23:12:26 CST 2012
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ques
	 * @mbggenerated  Mon Sep 10 23:12:26 CST 2012
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ques
	 * @mbggenerated  Mon Sep 10 23:12:26 CST 2012
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table ques
	 * @mbggenerated  Mon Sep 10 23:12:26 CST 2012
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		protected void addCriterionForJDBCDate(String condition, Date value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value.getTime()), property);
		}

		protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property + " cannot be null or empty");
			}
			List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
			Iterator<Date> iter = values.iterator();
			while (iter.hasNext()) {
				dateList.add(new java.sql.Date(iter.next().getTime()));
			}
			addCriterion(condition, dateList, property);
		}

		protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Long value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Long value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Long value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Long value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Long value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Long value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Long> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Long> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Long value1, Long value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Long value1, Long value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andQuesNaireIdIsNull() {
			addCriterion("ques_naire_id is null");
			return (Criteria) this;
		}

		public Criteria andQuesNaireIdIsNotNull() {
			addCriterion("ques_naire_id is not null");
			return (Criteria) this;
		}

		public Criteria andQuesNaireIdEqualTo(Long value) {
			addCriterion("ques_naire_id =", value, "quesNaireId");
			return (Criteria) this;
		}

		public Criteria andQuesNaireIdNotEqualTo(Long value) {
			addCriterion("ques_naire_id <>", value, "quesNaireId");
			return (Criteria) this;
		}

		public Criteria andQuesNaireIdGreaterThan(Long value) {
			addCriterion("ques_naire_id >", value, "quesNaireId");
			return (Criteria) this;
		}

		public Criteria andQuesNaireIdGreaterThanOrEqualTo(Long value) {
			addCriterion("ques_naire_id >=", value, "quesNaireId");
			return (Criteria) this;
		}

		public Criteria andQuesNaireIdLessThan(Long value) {
			addCriterion("ques_naire_id <", value, "quesNaireId");
			return (Criteria) this;
		}

		public Criteria andQuesNaireIdLessThanOrEqualTo(Long value) {
			addCriterion("ques_naire_id <=", value, "quesNaireId");
			return (Criteria) this;
		}

		public Criteria andQuesNaireIdIn(List<Long> values) {
			addCriterion("ques_naire_id in", values, "quesNaireId");
			return (Criteria) this;
		}

		public Criteria andQuesNaireIdNotIn(List<Long> values) {
			addCriterion("ques_naire_id not in", values, "quesNaireId");
			return (Criteria) this;
		}

		public Criteria andQuesNaireIdBetween(Long value1, Long value2) {
			addCriterion("ques_naire_id between", value1, value2, "quesNaireId");
			return (Criteria) this;
		}

		public Criteria andQuesNaireIdNotBetween(Long value1, Long value2) {
			addCriterion("ques_naire_id not between", value1, value2, "quesNaireId");
			return (Criteria) this;
		}

		public Criteria andTypeIsNull() {
			addCriterion("type is null");
			return (Criteria) this;
		}

		public Criteria andTypeIsNotNull() {
			addCriterion("type is not null");
			return (Criteria) this;
		}

		public Criteria andTypeEqualTo(Integer value) {
			addCriterion("type =", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeNotEqualTo(Integer value) {
			addCriterion("type <>", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeGreaterThan(Integer value) {
			addCriterion("type >", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeGreaterThanOrEqualTo(Integer value) {
			addCriterion("type >=", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeLessThan(Integer value) {
			addCriterion("type <", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeLessThanOrEqualTo(Integer value) {
			addCriterion("type <=", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeIn(List<Integer> values) {
			addCriterion("type in", values, "type");
			return (Criteria) this;
		}

		public Criteria andTypeNotIn(List<Integer> values) {
			addCriterion("type not in", values, "type");
			return (Criteria) this;
		}

		public Criteria andTypeBetween(Integer value1, Integer value2) {
			addCriterion("type between", value1, value2, "type");
			return (Criteria) this;
		}

		public Criteria andTypeNotBetween(Integer value1, Integer value2) {
			addCriterion("type not between", value1, value2, "type");
			return (Criteria) this;
		}

		public Criteria andPageNoIsNull() {
			addCriterion("page_no is null");
			return (Criteria) this;
		}

		public Criteria andPageNoIsNotNull() {
			addCriterion("page_no is not null");
			return (Criteria) this;
		}

		public Criteria andPageNoEqualTo(Integer value) {
			addCriterion("page_no =", value, "pageNo");
			return (Criteria) this;
		}

		public Criteria andPageNoNotEqualTo(Integer value) {
			addCriterion("page_no <>", value, "pageNo");
			return (Criteria) this;
		}

		public Criteria andPageNoGreaterThan(Integer value) {
			addCriterion("page_no >", value, "pageNo");
			return (Criteria) this;
		}

		public Criteria andPageNoGreaterThanOrEqualTo(Integer value) {
			addCriterion("page_no >=", value, "pageNo");
			return (Criteria) this;
		}

		public Criteria andPageNoLessThan(Integer value) {
			addCriterion("page_no <", value, "pageNo");
			return (Criteria) this;
		}

		public Criteria andPageNoLessThanOrEqualTo(Integer value) {
			addCriterion("page_no <=", value, "pageNo");
			return (Criteria) this;
		}

		public Criteria andPageNoIn(List<Integer> values) {
			addCriterion("page_no in", values, "pageNo");
			return (Criteria) this;
		}

		public Criteria andPageNoNotIn(List<Integer> values) {
			addCriterion("page_no not in", values, "pageNo");
			return (Criteria) this;
		}

		public Criteria andPageNoBetween(Integer value1, Integer value2) {
			addCriterion("page_no between", value1, value2, "pageNo");
			return (Criteria) this;
		}

		public Criteria andPageNoNotBetween(Integer value1, Integer value2) {
			addCriterion("page_no not between", value1, value2, "pageNo");
			return (Criteria) this;
		}

		public Criteria andSerialNoIsNull() {
			addCriterion("serial_no is null");
			return (Criteria) this;
		}

		public Criteria andSerialNoIsNotNull() {
			addCriterion("serial_no is not null");
			return (Criteria) this;
		}

		public Criteria andSerialNoEqualTo(Integer value) {
			addCriterion("serial_no =", value, "serialNo");
			return (Criteria) this;
		}

		public Criteria andSerialNoNotEqualTo(Integer value) {
			addCriterion("serial_no <>", value, "serialNo");
			return (Criteria) this;
		}

		public Criteria andSerialNoGreaterThan(Integer value) {
			addCriterion("serial_no >", value, "serialNo");
			return (Criteria) this;
		}

		public Criteria andSerialNoGreaterThanOrEqualTo(Integer value) {
			addCriterion("serial_no >=", value, "serialNo");
			return (Criteria) this;
		}

		public Criteria andSerialNoLessThan(Integer value) {
			addCriterion("serial_no <", value, "serialNo");
			return (Criteria) this;
		}

		public Criteria andSerialNoLessThanOrEqualTo(Integer value) {
			addCriterion("serial_no <=", value, "serialNo");
			return (Criteria) this;
		}

		public Criteria andSerialNoIn(List<Integer> values) {
			addCriterion("serial_no in", values, "serialNo");
			return (Criteria) this;
		}

		public Criteria andSerialNoNotIn(List<Integer> values) {
			addCriterion("serial_no not in", values, "serialNo");
			return (Criteria) this;
		}

		public Criteria andSerialNoBetween(Integer value1, Integer value2) {
			addCriterion("serial_no between", value1, value2, "serialNo");
			return (Criteria) this;
		}

		public Criteria andSerialNoNotBetween(Integer value1, Integer value2) {
			addCriterion("serial_no not between", value1, value2, "serialNo");
			return (Criteria) this;
		}

		public Criteria andBusiNoIsNull() {
			addCriterion("busi_no is null");
			return (Criteria) this;
		}

		public Criteria andBusiNoIsNotNull() {
			addCriterion("busi_no is not null");
			return (Criteria) this;
		}

		public Criteria andBusiNoEqualTo(String value) {
			addCriterion("busi_no =", value, "busiNo");
			return (Criteria) this;
		}

		public Criteria andBusiNoNotEqualTo(String value) {
			addCriterion("busi_no <>", value, "busiNo");
			return (Criteria) this;
		}

		public Criteria andBusiNoGreaterThan(String value) {
			addCriterion("busi_no >", value, "busiNo");
			return (Criteria) this;
		}

		public Criteria andBusiNoGreaterThanOrEqualTo(String value) {
			addCriterion("busi_no >=", value, "busiNo");
			return (Criteria) this;
		}

		public Criteria andBusiNoLessThan(String value) {
			addCriterion("busi_no <", value, "busiNo");
			return (Criteria) this;
		}

		public Criteria andBusiNoLessThanOrEqualTo(String value) {
			addCriterion("busi_no <=", value, "busiNo");
			return (Criteria) this;
		}

		public Criteria andBusiNoLike(String value) {
			addCriterion("busi_no like", value, "busiNo");
			return (Criteria) this;
		}

		public Criteria andBusiNoNotLike(String value) {
			addCriterion("busi_no not like", value, "busiNo");
			return (Criteria) this;
		}

		public Criteria andBusiNoIn(List<String> values) {
			addCriterion("busi_no in", values, "busiNo");
			return (Criteria) this;
		}

		public Criteria andBusiNoNotIn(List<String> values) {
			addCriterion("busi_no not in", values, "busiNo");
			return (Criteria) this;
		}

		public Criteria andBusiNoBetween(String value1, String value2) {
			addCriterion("busi_no between", value1, value2, "busiNo");
			return (Criteria) this;
		}

		public Criteria andBusiNoNotBetween(String value1, String value2) {
			addCriterion("busi_no not between", value1, value2, "busiNo");
			return (Criteria) this;
		}

		public Criteria andTitleIsNull() {
			addCriterion("title is null");
			return (Criteria) this;
		}

		public Criteria andTitleIsNotNull() {
			addCriterion("title is not null");
			return (Criteria) this;
		}

		public Criteria andTitleEqualTo(String value) {
			addCriterion("title =", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleNotEqualTo(String value) {
			addCriterion("title <>", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleGreaterThan(String value) {
			addCriterion("title >", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleGreaterThanOrEqualTo(String value) {
			addCriterion("title >=", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleLessThan(String value) {
			addCriterion("title <", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleLessThanOrEqualTo(String value) {
			addCriterion("title <=", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleLike(String value) {
			addCriterion("title like", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleNotLike(String value) {
			addCriterion("title not like", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleIn(List<String> values) {
			addCriterion("title in", values, "title");
			return (Criteria) this;
		}

		public Criteria andTitleNotIn(List<String> values) {
			addCriterion("title not in", values, "title");
			return (Criteria) this;
		}

		public Criteria andTitleBetween(String value1, String value2) {
			addCriterion("title between", value1, value2, "title");
			return (Criteria) this;
		}

		public Criteria andTitleNotBetween(String value1, String value2) {
			addCriterion("title not between", value1, value2, "title");
			return (Criteria) this;
		}

		public Criteria andContentIsNull() {
			addCriterion("content is null");
			return (Criteria) this;
		}

		public Criteria andContentIsNotNull() {
			addCriterion("content is not null");
			return (Criteria) this;
		}

		public Criteria andContentEqualTo(String value) {
			addCriterion("content =", value, "content");
			return (Criteria) this;
		}

		public Criteria andContentNotEqualTo(String value) {
			addCriterion("content <>", value, "content");
			return (Criteria) this;
		}

		public Criteria andContentGreaterThan(String value) {
			addCriterion("content >", value, "content");
			return (Criteria) this;
		}

		public Criteria andContentGreaterThanOrEqualTo(String value) {
			addCriterion("content >=", value, "content");
			return (Criteria) this;
		}

		public Criteria andContentLessThan(String value) {
			addCriterion("content <", value, "content");
			return (Criteria) this;
		}

		public Criteria andContentLessThanOrEqualTo(String value) {
			addCriterion("content <=", value, "content");
			return (Criteria) this;
		}

		public Criteria andContentLike(String value) {
			addCriterion("content like", value, "content");
			return (Criteria) this;
		}

		public Criteria andContentNotLike(String value) {
			addCriterion("content not like", value, "content");
			return (Criteria) this;
		}

		public Criteria andContentIn(List<String> values) {
			addCriterion("content in", values, "content");
			return (Criteria) this;
		}

		public Criteria andContentNotIn(List<String> values) {
			addCriterion("content not in", values, "content");
			return (Criteria) this;
		}

		public Criteria andContentBetween(String value1, String value2) {
			addCriterion("content between", value1, value2, "content");
			return (Criteria) this;
		}

		public Criteria andContentNotBetween(String value1, String value2) {
			addCriterion("content not between", value1, value2, "content");
			return (Criteria) this;
		}

		public Criteria andDescriptIsNull() {
			addCriterion("descript is null");
			return (Criteria) this;
		}

		public Criteria andDescriptIsNotNull() {
			addCriterion("descript is not null");
			return (Criteria) this;
		}

		public Criteria andDescriptEqualTo(String value) {
			addCriterion("descript =", value, "descript");
			return (Criteria) this;
		}

		public Criteria andDescriptNotEqualTo(String value) {
			addCriterion("descript <>", value, "descript");
			return (Criteria) this;
		}

		public Criteria andDescriptGreaterThan(String value) {
			addCriterion("descript >", value, "descript");
			return (Criteria) this;
		}

		public Criteria andDescriptGreaterThanOrEqualTo(String value) {
			addCriterion("descript >=", value, "descript");
			return (Criteria) this;
		}

		public Criteria andDescriptLessThan(String value) {
			addCriterion("descript <", value, "descript");
			return (Criteria) this;
		}

		public Criteria andDescriptLessThanOrEqualTo(String value) {
			addCriterion("descript <=", value, "descript");
			return (Criteria) this;
		}

		public Criteria andDescriptLike(String value) {
			addCriterion("descript like", value, "descript");
			return (Criteria) this;
		}

		public Criteria andDescriptNotLike(String value) {
			addCriterion("descript not like", value, "descript");
			return (Criteria) this;
		}

		public Criteria andDescriptIn(List<String> values) {
			addCriterion("descript in", values, "descript");
			return (Criteria) this;
		}

		public Criteria andDescriptNotIn(List<String> values) {
			addCriterion("descript not in", values, "descript");
			return (Criteria) this;
		}

		public Criteria andDescriptBetween(String value1, String value2) {
			addCriterion("descript between", value1, value2, "descript");
			return (Criteria) this;
		}

		public Criteria andDescriptNotBetween(String value1, String value2) {
			addCriterion("descript not between", value1, value2, "descript");
			return (Criteria) this;
		}

		public Criteria andMustAnswerIsNull() {
			addCriterion("must_answer is null");
			return (Criteria) this;
		}

		public Criteria andMustAnswerIsNotNull() {
			addCriterion("must_answer is not null");
			return (Criteria) this;
		}

		public Criteria andMustAnswerEqualTo(Integer value) {
			addCriterion("must_answer =", value, "mustAnswer");
			return (Criteria) this;
		}

		public Criteria andMustAnswerNotEqualTo(Integer value) {
			addCriterion("must_answer <>", value, "mustAnswer");
			return (Criteria) this;
		}

		public Criteria andMustAnswerGreaterThan(Integer value) {
			addCriterion("must_answer >", value, "mustAnswer");
			return (Criteria) this;
		}

		public Criteria andMustAnswerGreaterThanOrEqualTo(Integer value) {
			addCriterion("must_answer >=", value, "mustAnswer");
			return (Criteria) this;
		}

		public Criteria andMustAnswerLessThan(Integer value) {
			addCriterion("must_answer <", value, "mustAnswer");
			return (Criteria) this;
		}

		public Criteria andMustAnswerLessThanOrEqualTo(Integer value) {
			addCriterion("must_answer <=", value, "mustAnswer");
			return (Criteria) this;
		}

		public Criteria andMustAnswerIn(List<Integer> values) {
			addCriterion("must_answer in", values, "mustAnswer");
			return (Criteria) this;
		}

		public Criteria andMustAnswerNotIn(List<Integer> values) {
			addCriterion("must_answer not in", values, "mustAnswer");
			return (Criteria) this;
		}

		public Criteria andMustAnswerBetween(Integer value1, Integer value2) {
			addCriterion("must_answer between", value1, value2, "mustAnswer");
			return (Criteria) this;
		}

		public Criteria andMustAnswerNotBetween(Integer value1, Integer value2) {
			addCriterion("must_answer not between", value1, value2, "mustAnswer");
			return (Criteria) this;
		}

		public Criteria andCreateDateIsNull() {
			addCriterion("create_date is null");
			return (Criteria) this;
		}

		public Criteria andCreateDateIsNotNull() {
			addCriterion("create_date is not null");
			return (Criteria) this;
		}

		public Criteria andCreateDateEqualTo(Date value) {
			addCriterionForJDBCDate("create_date =", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateNotEqualTo(Date value) {
			addCriterionForJDBCDate("create_date <>", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateGreaterThan(Date value) {
			addCriterionForJDBCDate("create_date >", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("create_date >=", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateLessThan(Date value) {
			addCriterionForJDBCDate("create_date <", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("create_date <=", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateIn(List<Date> values) {
			addCriterionForJDBCDate("create_date in", values, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateNotIn(List<Date> values) {
			addCriterionForJDBCDate("create_date not in", values, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("create_date between", value1, value2, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("create_date not between", value1, value2, "createDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateIsNull() {
			addCriterion("update_date is null");
			return (Criteria) this;
		}

		public Criteria andUpdateDateIsNotNull() {
			addCriterion("update_date is not null");
			return (Criteria) this;
		}

		public Criteria andUpdateDateEqualTo(Date value) {
			addCriterionForJDBCDate("update_date =", value, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateNotEqualTo(Date value) {
			addCriterionForJDBCDate("update_date <>", value, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateGreaterThan(Date value) {
			addCriterionForJDBCDate("update_date >", value, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("update_date >=", value, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateLessThan(Date value) {
			addCriterionForJDBCDate("update_date <", value, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("update_date <=", value, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateIn(List<Date> values) {
			addCriterionForJDBCDate("update_date in", values, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateNotIn(List<Date> values) {
			addCriterionForJDBCDate("update_date not in", values, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("update_date between", value1, value2, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("update_date not between", value1, value2, "updateDate");
			return (Criteria) this;
		}

		public Criteria andVersionIsNull() {
			addCriterion("version is null");
			return (Criteria) this;
		}

		public Criteria andVersionIsNotNull() {
			addCriterion("version is not null");
			return (Criteria) this;
		}

		public Criteria andVersionEqualTo(Integer value) {
			addCriterion("version =", value, "version");
			return (Criteria) this;
		}

		public Criteria andVersionNotEqualTo(Integer value) {
			addCriterion("version <>", value, "version");
			return (Criteria) this;
		}

		public Criteria andVersionGreaterThan(Integer value) {
			addCriterion("version >", value, "version");
			return (Criteria) this;
		}

		public Criteria andVersionGreaterThanOrEqualTo(Integer value) {
			addCriterion("version >=", value, "version");
			return (Criteria) this;
		}

		public Criteria andVersionLessThan(Integer value) {
			addCriterion("version <", value, "version");
			return (Criteria) this;
		}

		public Criteria andVersionLessThanOrEqualTo(Integer value) {
			addCriterion("version <=", value, "version");
			return (Criteria) this;
		}

		public Criteria andVersionIn(List<Integer> values) {
			addCriterion("version in", values, "version");
			return (Criteria) this;
		}

		public Criteria andVersionNotIn(List<Integer> values) {
			addCriterion("version not in", values, "version");
			return (Criteria) this;
		}

		public Criteria andVersionBetween(Integer value1, Integer value2) {
			addCriterion("version between", value1, value2, "version");
			return (Criteria) this;
		}

		public Criteria andVersionNotBetween(Integer value1, Integer value2) {
			addCriterion("version not between", value1, value2, "version");
			return (Criteria) this;
		}

		public Criteria andRemarkIsNull() {
			addCriterion("remark is null");
			return (Criteria) this;
		}

		public Criteria andRemarkIsNotNull() {
			addCriterion("remark is not null");
			return (Criteria) this;
		}

		public Criteria andRemarkEqualTo(String value) {
			addCriterion("remark =", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkNotEqualTo(String value) {
			addCriterion("remark <>", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkGreaterThan(String value) {
			addCriterion("remark >", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkGreaterThanOrEqualTo(String value) {
			addCriterion("remark >=", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkLessThan(String value) {
			addCriterion("remark <", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkLessThanOrEqualTo(String value) {
			addCriterion("remark <=", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkLike(String value) {
			addCriterion("remark like", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkNotLike(String value) {
			addCriterion("remark not like", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkIn(List<String> values) {
			addCriterion("remark in", values, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkNotIn(List<String> values) {
			addCriterion("remark not in", values, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkBetween(String value1, String value2) {
			addCriterion("remark between", value1, value2, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkNotBetween(String value1, String value2) {
			addCriterion("remark not between", value1, value2, "remark");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table ques
	 * @mbggenerated  Mon Sep 10 23:12:26 CST 2012
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ques
     *
     * @mbggenerated do_not_delete_during_merge Sun Jul 29 21:04:38 CST 2012
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}