package com.survey.panelsns.model.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class SurveyExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table survey
	 * @mbggenerated  Mon Sep 10 23:12:27 CST 2012
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table survey
	 * @mbggenerated  Mon Sep 10 23:12:27 CST 2012
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table survey
	 * @mbggenerated  Mon Sep 10 23:12:27 CST 2012
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table survey
	 * @mbggenerated  Mon Sep 10 23:12:27 CST 2012
	 */
	public SurveyExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table survey
	 * @mbggenerated  Mon Sep 10 23:12:27 CST 2012
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table survey
	 * @mbggenerated  Mon Sep 10 23:12:27 CST 2012
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table survey
	 * @mbggenerated  Mon Sep 10 23:12:27 CST 2012
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table survey
	 * @mbggenerated  Mon Sep 10 23:12:27 CST 2012
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table survey
	 * @mbggenerated  Mon Sep 10 23:12:27 CST 2012
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table survey
	 * @mbggenerated  Mon Sep 10 23:12:27 CST 2012
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table survey
	 * @mbggenerated  Mon Sep 10 23:12:27 CST 2012
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table survey
	 * @mbggenerated  Mon Sep 10 23:12:27 CST 2012
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table survey
	 * @mbggenerated  Mon Sep 10 23:12:27 CST 2012
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table survey
	 * @mbggenerated  Mon Sep 10 23:12:27 CST 2012
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table survey
	 * @mbggenerated  Mon Sep 10 23:12:27 CST 2012
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		protected void addCriterionForJDBCDate(String condition, Date value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value.getTime()), property);
		}

		protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property + " cannot be null or empty");
			}
			List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
			Iterator<Date> iter = values.iterator();
			while (iter.hasNext()) {
				dateList.add(new java.sql.Date(iter.next().getTime()));
			}
			addCriterion(condition, dateList, property);
		}

		protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Long value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Long value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Long value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Long value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Long value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Long value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Long> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Long> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Long value1, Long value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Long value1, Long value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andProjectIdIsNull() {
			addCriterion("project_id is null");
			return (Criteria) this;
		}

		public Criteria andProjectIdIsNotNull() {
			addCriterion("project_id is not null");
			return (Criteria) this;
		}

		public Criteria andProjectIdEqualTo(Long value) {
			addCriterion("project_id =", value, "projectId");
			return (Criteria) this;
		}

		public Criteria andProjectIdNotEqualTo(Long value) {
			addCriterion("project_id <>", value, "projectId");
			return (Criteria) this;
		}

		public Criteria andProjectIdGreaterThan(Long value) {
			addCriterion("project_id >", value, "projectId");
			return (Criteria) this;
		}

		public Criteria andProjectIdGreaterThanOrEqualTo(Long value) {
			addCriterion("project_id >=", value, "projectId");
			return (Criteria) this;
		}

		public Criteria andProjectIdLessThan(Long value) {
			addCriterion("project_id <", value, "projectId");
			return (Criteria) this;
		}

		public Criteria andProjectIdLessThanOrEqualTo(Long value) {
			addCriterion("project_id <=", value, "projectId");
			return (Criteria) this;
		}

		public Criteria andProjectIdIn(List<Long> values) {
			addCriterion("project_id in", values, "projectId");
			return (Criteria) this;
		}

		public Criteria andProjectIdNotIn(List<Long> values) {
			addCriterion("project_id not in", values, "projectId");
			return (Criteria) this;
		}

		public Criteria andProjectIdBetween(Long value1, Long value2) {
			addCriterion("project_id between", value1, value2, "projectId");
			return (Criteria) this;
		}

		public Criteria andProjectIdNotBetween(Long value1, Long value2) {
			addCriterion("project_id not between", value1, value2, "projectId");
			return (Criteria) this;
		}

		public Criteria andIndustryIsNull() {
			addCriterion("industry is null");
			return (Criteria) this;
		}

		public Criteria andIndustryIsNotNull() {
			addCriterion("industry is not null");
			return (Criteria) this;
		}

		public Criteria andIndustryEqualTo(Integer value) {
			addCriterion("industry =", value, "industry");
			return (Criteria) this;
		}

		public Criteria andIndustryNotEqualTo(Integer value) {
			addCriterion("industry <>", value, "industry");
			return (Criteria) this;
		}

		public Criteria andIndustryGreaterThan(Integer value) {
			addCriterion("industry >", value, "industry");
			return (Criteria) this;
		}

		public Criteria andIndustryGreaterThanOrEqualTo(Integer value) {
			addCriterion("industry >=", value, "industry");
			return (Criteria) this;
		}

		public Criteria andIndustryLessThan(Integer value) {
			addCriterion("industry <", value, "industry");
			return (Criteria) this;
		}

		public Criteria andIndustryLessThanOrEqualTo(Integer value) {
			addCriterion("industry <=", value, "industry");
			return (Criteria) this;
		}

		public Criteria andIndustryIn(List<Integer> values) {
			addCriterion("industry in", values, "industry");
			return (Criteria) this;
		}

		public Criteria andIndustryNotIn(List<Integer> values) {
			addCriterion("industry not in", values, "industry");
			return (Criteria) this;
		}

		public Criteria andIndustryBetween(Integer value1, Integer value2) {
			addCriterion("industry between", value1, value2, "industry");
			return (Criteria) this;
		}

		public Criteria andIndustryNotBetween(Integer value1, Integer value2) {
			addCriterion("industry not between", value1, value2, "industry");
			return (Criteria) this;
		}

		public Criteria andNameIsNull() {
			addCriterion("name is null");
			return (Criteria) this;
		}

		public Criteria andNameIsNotNull() {
			addCriterion("name is not null");
			return (Criteria) this;
		}

		public Criteria andNameEqualTo(String value) {
			addCriterion("name =", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotEqualTo(String value) {
			addCriterion("name <>", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThan(String value) {
			addCriterion("name >", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThanOrEqualTo(String value) {
			addCriterion("name >=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThan(String value) {
			addCriterion("name <", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThanOrEqualTo(String value) {
			addCriterion("name <=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLike(String value) {
			addCriterion("name like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotLike(String value) {
			addCriterion("name not like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameIn(List<String> values) {
			addCriterion("name in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotIn(List<String> values) {
			addCriterion("name not in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameBetween(String value1, String value2) {
			addCriterion("name between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotBetween(String value1, String value2) {
			addCriterion("name not between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andNeedPanelNumIsNull() {
			addCriterion("need_panel_num is null");
			return (Criteria) this;
		}

		public Criteria andNeedPanelNumIsNotNull() {
			addCriterion("need_panel_num is not null");
			return (Criteria) this;
		}

		public Criteria andNeedPanelNumEqualTo(Integer value) {
			addCriterion("need_panel_num =", value, "needPanelNum");
			return (Criteria) this;
		}

		public Criteria andNeedPanelNumNotEqualTo(Integer value) {
			addCriterion("need_panel_num <>", value, "needPanelNum");
			return (Criteria) this;
		}

		public Criteria andNeedPanelNumGreaterThan(Integer value) {
			addCriterion("need_panel_num >", value, "needPanelNum");
			return (Criteria) this;
		}

		public Criteria andNeedPanelNumGreaterThanOrEqualTo(Integer value) {
			addCriterion("need_panel_num >=", value, "needPanelNum");
			return (Criteria) this;
		}

		public Criteria andNeedPanelNumLessThan(Integer value) {
			addCriterion("need_panel_num <", value, "needPanelNum");
			return (Criteria) this;
		}

		public Criteria andNeedPanelNumLessThanOrEqualTo(Integer value) {
			addCriterion("need_panel_num <=", value, "needPanelNum");
			return (Criteria) this;
		}

		public Criteria andNeedPanelNumIn(List<Integer> values) {
			addCriterion("need_panel_num in", values, "needPanelNum");
			return (Criteria) this;
		}

		public Criteria andNeedPanelNumNotIn(List<Integer> values) {
			addCriterion("need_panel_num not in", values, "needPanelNum");
			return (Criteria) this;
		}

		public Criteria andNeedPanelNumBetween(Integer value1, Integer value2) {
			addCriterion("need_panel_num between", value1, value2, "needPanelNum");
			return (Criteria) this;
		}

		public Criteria andNeedPanelNumNotBetween(Integer value1, Integer value2) {
			addCriterion("need_panel_num not between", value1, value2, "needPanelNum");
			return (Criteria) this;
		}

		public Criteria andEndowPointIsNull() {
			addCriterion("endow_point is null");
			return (Criteria) this;
		}

		public Criteria andEndowPointIsNotNull() {
			addCriterion("endow_point is not null");
			return (Criteria) this;
		}

		public Criteria andEndowPointEqualTo(Integer value) {
			addCriterion("endow_point =", value, "endowPoint");
			return (Criteria) this;
		}

		public Criteria andEndowPointNotEqualTo(Integer value) {
			addCriterion("endow_point <>", value, "endowPoint");
			return (Criteria) this;
		}

		public Criteria andEndowPointGreaterThan(Integer value) {
			addCriterion("endow_point >", value, "endowPoint");
			return (Criteria) this;
		}

		public Criteria andEndowPointGreaterThanOrEqualTo(Integer value) {
			addCriterion("endow_point >=", value, "endowPoint");
			return (Criteria) this;
		}

		public Criteria andEndowPointLessThan(Integer value) {
			addCriterion("endow_point <", value, "endowPoint");
			return (Criteria) this;
		}

		public Criteria andEndowPointLessThanOrEqualTo(Integer value) {
			addCriterion("endow_point <=", value, "endowPoint");
			return (Criteria) this;
		}

		public Criteria andEndowPointIn(List<Integer> values) {
			addCriterion("endow_point in", values, "endowPoint");
			return (Criteria) this;
		}

		public Criteria andEndowPointNotIn(List<Integer> values) {
			addCriterion("endow_point not in", values, "endowPoint");
			return (Criteria) this;
		}

		public Criteria andEndowPointBetween(Integer value1, Integer value2) {
			addCriterion("endow_point between", value1, value2, "endowPoint");
			return (Criteria) this;
		}

		public Criteria andEndowPointNotBetween(Integer value1, Integer value2) {
			addCriterion("endow_point not between", value1, value2, "endowPoint");
			return (Criteria) this;
		}

		public Criteria andHortationPointIsNull() {
			addCriterion("hortation_point is null");
			return (Criteria) this;
		}

		public Criteria andHortationPointIsNotNull() {
			addCriterion("hortation_point is not null");
			return (Criteria) this;
		}

		public Criteria andHortationPointEqualTo(Integer value) {
			addCriterion("hortation_point =", value, "hortationPoint");
			return (Criteria) this;
		}

		public Criteria andHortationPointNotEqualTo(Integer value) {
			addCriterion("hortation_point <>", value, "hortationPoint");
			return (Criteria) this;
		}

		public Criteria andHortationPointGreaterThan(Integer value) {
			addCriterion("hortation_point >", value, "hortationPoint");
			return (Criteria) this;
		}

		public Criteria andHortationPointGreaterThanOrEqualTo(Integer value) {
			addCriterion("hortation_point >=", value, "hortationPoint");
			return (Criteria) this;
		}

		public Criteria andHortationPointLessThan(Integer value) {
			addCriterion("hortation_point <", value, "hortationPoint");
			return (Criteria) this;
		}

		public Criteria andHortationPointLessThanOrEqualTo(Integer value) {
			addCriterion("hortation_point <=", value, "hortationPoint");
			return (Criteria) this;
		}

		public Criteria andHortationPointIn(List<Integer> values) {
			addCriterion("hortation_point in", values, "hortationPoint");
			return (Criteria) this;
		}

		public Criteria andHortationPointNotIn(List<Integer> values) {
			addCriterion("hortation_point not in", values, "hortationPoint");
			return (Criteria) this;
		}

		public Criteria andHortationPointBetween(Integer value1, Integer value2) {
			addCriterion("hortation_point between", value1, value2, "hortationPoint");
			return (Criteria) this;
		}

		public Criteria andHortationPointNotBetween(Integer value1, Integer value2) {
			addCriterion("hortation_point not between", value1, value2, "hortationPoint");
			return (Criteria) this;
		}

		public Criteria andBeginDateIsNull() {
			addCriterion("begin_date is null");
			return (Criteria) this;
		}

		public Criteria andBeginDateIsNotNull() {
			addCriterion("begin_date is not null");
			return (Criteria) this;
		}

		public Criteria andBeginDateEqualTo(Date value) {
			addCriterionForJDBCDate("begin_date =", value, "beginDate");
			return (Criteria) this;
		}

		public Criteria andBeginDateNotEqualTo(Date value) {
			addCriterionForJDBCDate("begin_date <>", value, "beginDate");
			return (Criteria) this;
		}

		public Criteria andBeginDateGreaterThan(Date value) {
			addCriterionForJDBCDate("begin_date >", value, "beginDate");
			return (Criteria) this;
		}

		public Criteria andBeginDateGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("begin_date >=", value, "beginDate");
			return (Criteria) this;
		}

		public Criteria andBeginDateLessThan(Date value) {
			addCriterionForJDBCDate("begin_date <", value, "beginDate");
			return (Criteria) this;
		}

		public Criteria andBeginDateLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("begin_date <=", value, "beginDate");
			return (Criteria) this;
		}

		public Criteria andBeginDateIn(List<Date> values) {
			addCriterionForJDBCDate("begin_date in", values, "beginDate");
			return (Criteria) this;
		}

		public Criteria andBeginDateNotIn(List<Date> values) {
			addCriterionForJDBCDate("begin_date not in", values, "beginDate");
			return (Criteria) this;
		}

		public Criteria andBeginDateBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("begin_date between", value1, value2, "beginDate");
			return (Criteria) this;
		}

		public Criteria andBeginDateNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("begin_date not between", value1, value2, "beginDate");
			return (Criteria) this;
		}

		public Criteria andEndDateIsNull() {
			addCriterion("end_date is null");
			return (Criteria) this;
		}

		public Criteria andEndDateIsNotNull() {
			addCriterion("end_date is not null");
			return (Criteria) this;
		}

		public Criteria andEndDateEqualTo(Date value) {
			addCriterionForJDBCDate("end_date =", value, "endDate");
			return (Criteria) this;
		}

		public Criteria andEndDateNotEqualTo(Date value) {
			addCriterionForJDBCDate("end_date <>", value, "endDate");
			return (Criteria) this;
		}

		public Criteria andEndDateGreaterThan(Date value) {
			addCriterionForJDBCDate("end_date >", value, "endDate");
			return (Criteria) this;
		}

		public Criteria andEndDateGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("end_date >=", value, "endDate");
			return (Criteria) this;
		}

		public Criteria andEndDateLessThan(Date value) {
			addCriterionForJDBCDate("end_date <", value, "endDate");
			return (Criteria) this;
		}

		public Criteria andEndDateLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("end_date <=", value, "endDate");
			return (Criteria) this;
		}

		public Criteria andEndDateIn(List<Date> values) {
			addCriterionForJDBCDate("end_date in", values, "endDate");
			return (Criteria) this;
		}

		public Criteria andEndDateNotIn(List<Date> values) {
			addCriterionForJDBCDate("end_date not in", values, "endDate");
			return (Criteria) this;
		}

		public Criteria andEndDateBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("end_date between", value1, value2, "endDate");
			return (Criteria) this;
		}

		public Criteria andEndDateNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("end_date not between", value1, value2, "endDate");
			return (Criteria) this;
		}

		public Criteria andCancleDateIsNull() {
			addCriterion("cancle_date is null");
			return (Criteria) this;
		}

		public Criteria andCancleDateIsNotNull() {
			addCriterion("cancle_date is not null");
			return (Criteria) this;
		}

		public Criteria andCancleDateEqualTo(Date value) {
			addCriterionForJDBCDate("cancle_date =", value, "cancleDate");
			return (Criteria) this;
		}

		public Criteria andCancleDateNotEqualTo(Date value) {
			addCriterionForJDBCDate("cancle_date <>", value, "cancleDate");
			return (Criteria) this;
		}

		public Criteria andCancleDateGreaterThan(Date value) {
			addCriterionForJDBCDate("cancle_date >", value, "cancleDate");
			return (Criteria) this;
		}

		public Criteria andCancleDateGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("cancle_date >=", value, "cancleDate");
			return (Criteria) this;
		}

		public Criteria andCancleDateLessThan(Date value) {
			addCriterionForJDBCDate("cancle_date <", value, "cancleDate");
			return (Criteria) this;
		}

		public Criteria andCancleDateLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("cancle_date <=", value, "cancleDate");
			return (Criteria) this;
		}

		public Criteria andCancleDateIn(List<Date> values) {
			addCriterionForJDBCDate("cancle_date in", values, "cancleDate");
			return (Criteria) this;
		}

		public Criteria andCancleDateNotIn(List<Date> values) {
			addCriterionForJDBCDate("cancle_date not in", values, "cancleDate");
			return (Criteria) this;
		}

		public Criteria andCancleDateBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("cancle_date between", value1, value2, "cancleDate");
			return (Criteria) this;
		}

		public Criteria andCancleDateNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("cancle_date not between", value1, value2, "cancleDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateIsNull() {
			addCriterion("create_date is null");
			return (Criteria) this;
		}

		public Criteria andCreateDateIsNotNull() {
			addCriterion("create_date is not null");
			return (Criteria) this;
		}

		public Criteria andCreateDateEqualTo(Date value) {
			addCriterionForJDBCDate("create_date =", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateNotEqualTo(Date value) {
			addCriterionForJDBCDate("create_date <>", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateGreaterThan(Date value) {
			addCriterionForJDBCDate("create_date >", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("create_date >=", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateLessThan(Date value) {
			addCriterionForJDBCDate("create_date <", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("create_date <=", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateIn(List<Date> values) {
			addCriterionForJDBCDate("create_date in", values, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateNotIn(List<Date> values) {
			addCriterionForJDBCDate("create_date not in", values, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("create_date between", value1, value2, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("create_date not between", value1, value2, "createDate");
			return (Criteria) this;
		}

		public Criteria andDescriptIsNull() {
			addCriterion("descript is null");
			return (Criteria) this;
		}

		public Criteria andDescriptIsNotNull() {
			addCriterion("descript is not null");
			return (Criteria) this;
		}

		public Criteria andDescriptEqualTo(String value) {
			addCriterion("descript =", value, "descript");
			return (Criteria) this;
		}

		public Criteria andDescriptNotEqualTo(String value) {
			addCriterion("descript <>", value, "descript");
			return (Criteria) this;
		}

		public Criteria andDescriptGreaterThan(String value) {
			addCriterion("descript >", value, "descript");
			return (Criteria) this;
		}

		public Criteria andDescriptGreaterThanOrEqualTo(String value) {
			addCriterion("descript >=", value, "descript");
			return (Criteria) this;
		}

		public Criteria andDescriptLessThan(String value) {
			addCriterion("descript <", value, "descript");
			return (Criteria) this;
		}

		public Criteria andDescriptLessThanOrEqualTo(String value) {
			addCriterion("descript <=", value, "descript");
			return (Criteria) this;
		}

		public Criteria andDescriptLike(String value) {
			addCriterion("descript like", value, "descript");
			return (Criteria) this;
		}

		public Criteria andDescriptNotLike(String value) {
			addCriterion("descript not like", value, "descript");
			return (Criteria) this;
		}

		public Criteria andDescriptIn(List<String> values) {
			addCriterion("descript in", values, "descript");
			return (Criteria) this;
		}

		public Criteria andDescriptNotIn(List<String> values) {
			addCriterion("descript not in", values, "descript");
			return (Criteria) this;
		}

		public Criteria andDescriptBetween(String value1, String value2) {
			addCriterion("descript between", value1, value2, "descript");
			return (Criteria) this;
		}

		public Criteria andDescriptNotBetween(String value1, String value2) {
			addCriterion("descript not between", value1, value2, "descript");
			return (Criteria) this;
		}

		public Criteria andStatusIsNull() {
			addCriterion("status is null");
			return (Criteria) this;
		}

		public Criteria andStatusIsNotNull() {
			addCriterion("status is not null");
			return (Criteria) this;
		}

		public Criteria andStatusEqualTo(Integer value) {
			addCriterion("status =", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotEqualTo(Integer value) {
			addCriterion("status <>", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThan(Integer value) {
			addCriterion("status >", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
			addCriterion("status >=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThan(Integer value) {
			addCriterion("status <", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThanOrEqualTo(Integer value) {
			addCriterion("status <=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusIn(List<Integer> values) {
			addCriterion("status in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotIn(List<Integer> values) {
			addCriterion("status not in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusBetween(Integer value1, Integer value2) {
			addCriterion("status between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotBetween(Integer value1, Integer value2) {
			addCriterion("status not between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andVersionIsNull() {
			addCriterion("version is null");
			return (Criteria) this;
		}

		public Criteria andVersionIsNotNull() {
			addCriterion("version is not null");
			return (Criteria) this;
		}

		public Criteria andVersionEqualTo(Integer value) {
			addCriterion("version =", value, "version");
			return (Criteria) this;
		}

		public Criteria andVersionNotEqualTo(Integer value) {
			addCriterion("version <>", value, "version");
			return (Criteria) this;
		}

		public Criteria andVersionGreaterThan(Integer value) {
			addCriterion("version >", value, "version");
			return (Criteria) this;
		}

		public Criteria andVersionGreaterThanOrEqualTo(Integer value) {
			addCriterion("version >=", value, "version");
			return (Criteria) this;
		}

		public Criteria andVersionLessThan(Integer value) {
			addCriterion("version <", value, "version");
			return (Criteria) this;
		}

		public Criteria andVersionLessThanOrEqualTo(Integer value) {
			addCriterion("version <=", value, "version");
			return (Criteria) this;
		}

		public Criteria andVersionIn(List<Integer> values) {
			addCriterion("version in", values, "version");
			return (Criteria) this;
		}

		public Criteria andVersionNotIn(List<Integer> values) {
			addCriterion("version not in", values, "version");
			return (Criteria) this;
		}

		public Criteria andVersionBetween(Integer value1, Integer value2) {
			addCriterion("version between", value1, value2, "version");
			return (Criteria) this;
		}

		public Criteria andVersionNotBetween(Integer value1, Integer value2) {
			addCriterion("version not between", value1, value2, "version");
			return (Criteria) this;
		}

		public Criteria andRemarkIsNull() {
			addCriterion("remark is null");
			return (Criteria) this;
		}

		public Criteria andRemarkIsNotNull() {
			addCriterion("remark is not null");
			return (Criteria) this;
		}

		public Criteria andRemarkEqualTo(String value) {
			addCriterion("remark =", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkNotEqualTo(String value) {
			addCriterion("remark <>", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkGreaterThan(String value) {
			addCriterion("remark >", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkGreaterThanOrEqualTo(String value) {
			addCriterion("remark >=", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkLessThan(String value) {
			addCriterion("remark <", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkLessThanOrEqualTo(String value) {
			addCriterion("remark <=", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkLike(String value) {
			addCriterion("remark like", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkNotLike(String value) {
			addCriterion("remark not like", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkIn(List<String> values) {
			addCriterion("remark in", values, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkNotIn(List<String> values) {
			addCriterion("remark not in", values, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkBetween(String value1, String value2) {
			addCriterion("remark between", value1, value2, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkNotBetween(String value1, String value2) {
			addCriterion("remark not between", value1, value2, "remark");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table survey
	 * @mbggenerated  Mon Sep 10 23:12:27 CST 2012
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table survey
     *
     * @mbggenerated do_not_delete_during_merge Sun Jul 29 21:04:38 CST 2012
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}