package com.survey.panelsns.model.entity;

import java.util.Date;

public class Survey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column survey.id
	 * @mbggenerated  Tue Sep 18 00:39:07 CST 2012
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column survey.project_id
	 * @mbggenerated  Tue Sep 18 00:39:07 CST 2012
	 */
	private Long projectId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column survey.industry
	 * @mbggenerated  Tue Sep 18 00:39:07 CST 2012
	 */
	private Integer industry;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column survey.name
	 * @mbggenerated  Tue Sep 18 00:39:07 CST 2012
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column survey.need_panel_num
	 * @mbggenerated  Tue Sep 18 00:39:07 CST 2012
	 */
	private Integer needPanelNum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column survey.endow_point
	 * @mbggenerated  Tue Sep 18 00:39:07 CST 2012
	 */
	private Integer endowPoint;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column survey.hortation_point
	 * @mbggenerated  Tue Sep 18 00:39:07 CST 2012
	 */
	private Integer hortationPoint;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column survey.begin_date
	 * @mbggenerated  Tue Sep 18 00:39:07 CST 2012
	 */
	private Date beginDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column survey.end_date
	 * @mbggenerated  Tue Sep 18 00:39:07 CST 2012
	 */
	private Date endDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column survey.cancle_date
	 * @mbggenerated  Tue Sep 18 00:39:07 CST 2012
	 */
	private Date cancleDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column survey.create_date
	 * @mbggenerated  Tue Sep 18 00:39:07 CST 2012
	 */
	private Date createDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column survey.descript
	 * @mbggenerated  Tue Sep 18 00:39:07 CST 2012
	 */
	private String descript;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column survey.status
	 * @mbggenerated  Tue Sep 18 00:39:07 CST 2012
	 */
	private Integer status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column survey.version
	 * @mbggenerated  Tue Sep 18 00:39:07 CST 2012
	 */
	private Integer version;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column survey.remark
	 * @mbggenerated  Tue Sep 18 00:39:07 CST 2012
	 */
	private String remark;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column survey.id
	 * @return  the value of survey.id
	 * @mbggenerated  Tue Sep 18 00:39:07 CST 2012
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column survey.id
	 * @param id  the value for survey.id
	 * @mbggenerated  Tue Sep 18 00:39:07 CST 2012
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column survey.project_id
	 * @return  the value of survey.project_id
	 * @mbggenerated  Tue Sep 18 00:39:07 CST 2012
	 */
	public Long getProjectId() {
		return projectId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column survey.project_id
	 * @param projectId  the value for survey.project_id
	 * @mbggenerated  Tue Sep 18 00:39:07 CST 2012
	 */
	public void setProjectId(Long projectId) {
		this.projectId = projectId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column survey.industry
	 * @return  the value of survey.industry
	 * @mbggenerated  Tue Sep 18 00:39:07 CST 2012
	 */
	public Integer getIndustry() {
		return industry;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column survey.industry
	 * @param industry  the value for survey.industry
	 * @mbggenerated  Tue Sep 18 00:39:07 CST 2012
	 */
	public void setIndustry(Integer industry) {
		this.industry = industry;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column survey.name
	 * @return  the value of survey.name
	 * @mbggenerated  Tue Sep 18 00:39:07 CST 2012
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column survey.name
	 * @param name  the value for survey.name
	 * @mbggenerated  Tue Sep 18 00:39:07 CST 2012
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column survey.need_panel_num
	 * @return  the value of survey.need_panel_num
	 * @mbggenerated  Tue Sep 18 00:39:07 CST 2012
	 */
	public Integer getNeedPanelNum() {
		return needPanelNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column survey.need_panel_num
	 * @param needPanelNum  the value for survey.need_panel_num
	 * @mbggenerated  Tue Sep 18 00:39:07 CST 2012
	 */
	public void setNeedPanelNum(Integer needPanelNum) {
		this.needPanelNum = needPanelNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column survey.endow_point
	 * @return  the value of survey.endow_point
	 * @mbggenerated  Tue Sep 18 00:39:07 CST 2012
	 */
	public Integer getEndowPoint() {
		return endowPoint;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column survey.endow_point
	 * @param endowPoint  the value for survey.endow_point
	 * @mbggenerated  Tue Sep 18 00:39:07 CST 2012
	 */
	public void setEndowPoint(Integer endowPoint) {
		this.endowPoint = endowPoint;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column survey.hortation_point
	 * @return  the value of survey.hortation_point
	 * @mbggenerated  Tue Sep 18 00:39:07 CST 2012
	 */
	public Integer getHortationPoint() {
		return hortationPoint;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column survey.hortation_point
	 * @param hortationPoint  the value for survey.hortation_point
	 * @mbggenerated  Tue Sep 18 00:39:07 CST 2012
	 */
	public void setHortationPoint(Integer hortationPoint) {
		this.hortationPoint = hortationPoint;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column survey.begin_date
	 * @return  the value of survey.begin_date
	 * @mbggenerated  Tue Sep 18 00:39:07 CST 2012
	 */
	public Date getBeginDate() {
		return beginDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column survey.begin_date
	 * @param beginDate  the value for survey.begin_date
	 * @mbggenerated  Tue Sep 18 00:39:07 CST 2012
	 */
	public void setBeginDate(Date beginDate) {
		this.beginDate = beginDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column survey.end_date
	 * @return  the value of survey.end_date
	 * @mbggenerated  Tue Sep 18 00:39:07 CST 2012
	 */
	public Date getEndDate() {
		return endDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column survey.end_date
	 * @param endDate  the value for survey.end_date
	 * @mbggenerated  Tue Sep 18 00:39:07 CST 2012
	 */
	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column survey.cancle_date
	 * @return  the value of survey.cancle_date
	 * @mbggenerated  Tue Sep 18 00:39:07 CST 2012
	 */
	public Date getCancleDate() {
		return cancleDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column survey.cancle_date
	 * @param cancleDate  the value for survey.cancle_date
	 * @mbggenerated  Tue Sep 18 00:39:07 CST 2012
	 */
	public void setCancleDate(Date cancleDate) {
		this.cancleDate = cancleDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column survey.create_date
	 * @return  the value of survey.create_date
	 * @mbggenerated  Tue Sep 18 00:39:07 CST 2012
	 */
	public Date getCreateDate() {
		return createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column survey.create_date
	 * @param createDate  the value for survey.create_date
	 * @mbggenerated  Tue Sep 18 00:39:07 CST 2012
	 */
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column survey.descript
	 * @return  the value of survey.descript
	 * @mbggenerated  Tue Sep 18 00:39:07 CST 2012
	 */
	public String getDescript() {
		return descript;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column survey.descript
	 * @param descript  the value for survey.descript
	 * @mbggenerated  Tue Sep 18 00:39:07 CST 2012
	 */
	public void setDescript(String descript) {
		this.descript = descript;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column survey.status
	 * @return  the value of survey.status
	 * @mbggenerated  Tue Sep 18 00:39:07 CST 2012
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column survey.status
	 * @param status  the value for survey.status
	 * @mbggenerated  Tue Sep 18 00:39:07 CST 2012
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column survey.version
	 * @return  the value of survey.version
	 * @mbggenerated  Tue Sep 18 00:39:07 CST 2012
	 */
	public Integer getVersion() {
		return version;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column survey.version
	 * @param version  the value for survey.version
	 * @mbggenerated  Tue Sep 18 00:39:07 CST 2012
	 */
	public void setVersion(Integer version) {
		this.version = version;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column survey.remark
	 * @return  the value of survey.remark
	 * @mbggenerated  Tue Sep 18 00:39:07 CST 2012
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column survey.remark
	 * @param remark  the value for survey.remark
	 * @mbggenerated  Tue Sep 18 00:39:07 CST 2012
	 */
	public void setRemark(String remark) {
		this.remark = remark;
	}
}