package com.survey.panelsns.model.entity;

import java.util.Date;

public class Templates {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column templates.id
	 * @mbggenerated  Sat Aug 25 14:14:03 CST 2012
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column templates.type
	 * @mbggenerated  Sat Aug 25 14:14:03 CST 2012
	 */
	private Integer type;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column templates.name
	 * @mbggenerated  Sat Aug 25 14:14:03 CST 2012
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column templates.path
	 * @mbggenerated  Sat Aug 25 14:14:03 CST 2012
	 */
	private String path;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column templates.descript
	 * @mbggenerated  Sat Aug 25 14:14:03 CST 2012
	 */
	private String descript;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column templates.create_date
	 * @mbggenerated  Sat Aug 25 14:14:03 CST 2012
	 */
	private Date createDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column templates.version
	 * @mbggenerated  Sat Aug 25 14:14:03 CST 2012
	 */
	private Integer version;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column templates.remark
	 * @mbggenerated  Sat Aug 25 14:14:03 CST 2012
	 */
	private String remark;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column templates.id
	 * @return  the value of templates.id
	 * @mbggenerated  Sat Aug 25 14:14:03 CST 2012
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column templates.id
	 * @param id  the value for templates.id
	 * @mbggenerated  Sat Aug 25 14:14:03 CST 2012
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column templates.type
	 * @return  the value of templates.type
	 * @mbggenerated  Sat Aug 25 14:14:03 CST 2012
	 */
	public Integer getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column templates.type
	 * @param type  the value for templates.type
	 * @mbggenerated  Sat Aug 25 14:14:03 CST 2012
	 */
	public void setType(Integer type) {
		this.type = type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column templates.name
	 * @return  the value of templates.name
	 * @mbggenerated  Sat Aug 25 14:14:03 CST 2012
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column templates.name
	 * @param name  the value for templates.name
	 * @mbggenerated  Sat Aug 25 14:14:03 CST 2012
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column templates.path
	 * @return  the value of templates.path
	 * @mbggenerated  Sat Aug 25 14:14:03 CST 2012
	 */
	public String getPath() {
		return path;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column templates.path
	 * @param path  the value for templates.path
	 * @mbggenerated  Sat Aug 25 14:14:03 CST 2012
	 */
	public void setPath(String path) {
		this.path = path;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column templates.descript
	 * @return  the value of templates.descript
	 * @mbggenerated  Sat Aug 25 14:14:03 CST 2012
	 */
	public String getDescript() {
		return descript;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column templates.descript
	 * @param descript  the value for templates.descript
	 * @mbggenerated  Sat Aug 25 14:14:03 CST 2012
	 */
	public void setDescript(String descript) {
		this.descript = descript;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column templates.create_date
	 * @return  the value of templates.create_date
	 * @mbggenerated  Sat Aug 25 14:14:03 CST 2012
	 */
	public Date getCreateDate() {
		return createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column templates.create_date
	 * @param createDate  the value for templates.create_date
	 * @mbggenerated  Sat Aug 25 14:14:03 CST 2012
	 */
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column templates.version
	 * @return  the value of templates.version
	 * @mbggenerated  Sat Aug 25 14:14:03 CST 2012
	 */
	public Integer getVersion() {
		return version;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column templates.version
	 * @param version  the value for templates.version
	 * @mbggenerated  Sat Aug 25 14:14:03 CST 2012
	 */
	public void setVersion(Integer version) {
		this.version = version;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column templates.remark
	 * @return  the value of templates.remark
	 * @mbggenerated  Sat Aug 25 14:14:03 CST 2012
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column templates.remark
	 * @param remark  the value for templates.remark
	 * @mbggenerated  Sat Aug 25 14:14:03 CST 2012
	 */
	public void setRemark(String remark) {
		this.remark = remark;
	}
}