package com.survey.panelsns.model.entity;

public class Users {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.id
	 * @mbggenerated  Sun Jul 29 21:06:13 CST 2012
	 */
	private Long id;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.id
	 * @return  the value of users.id
	 * @mbggenerated  Sun Jul 29 21:06:13 CST 2012
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.id
	 * @param id  the value for users.id
	 * @mbggenerated  Sun Jul 29 21:06:13 CST 2012
	 */
	public void setId(Long id) {
		this.id = id;
	}
}